import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ChevronLeft } from "lucide-react";
import { Suspense, useState } from "react";
import { policiesListQueryOptions } from "@/api/hooks/policies";
import { Button } from "@/components/ui/button";
import { RelayKeyForm } from "@/relay-keys/RelayKeyForm";
import { SecretReveal } from "@/relay-keys/SecretReveal";
import { PageLoader } from "@/shared/Spinner";

export const Route = createFileRoute("/_authenticated/relay-keys/new")({
	loader: ({ context }) =>
		context.queryClient.ensureQueryData(policiesListQueryOptions),
	component: NewRelayKeyPage,
});

function NewRelayKeyInner() {
	const navigate = useNavigate();
	const [plaintext, setPlaintext] = useState<string | null>(null);
	const [savedName, setSavedName] = useState<string | null>(null);

	if (plaintext !== null && savedName !== null) {
		return (
			<div className="flex flex-col gap-4 max-w-2xl">
				<div>
					<h1 className="text-xl font-semibold text-foreground">
						Relay key created
					</h1>
					<p className="mt-1 text-xs text-muted-foreground">
						Copy this secret now — it won't be shown again. Only the hash is
						stored.
					</p>
				</div>
				<SecretReveal secret={plaintext} />
				<div className="flex justify-end gap-2">
					<Button
						type="button"
						variant="outline"
						onClick={() =>
							void navigate({
								to: "/keys",
								search: { tab: "relay", q: "" },
							})
						}
					>
						Back to keys
					</Button>
					<Button
						type="button"
						onClick={() =>
							void navigate({
								to: "/relay-keys/$name",
								params: { name: savedName },
							})
						}
					>
						View key
					</Button>
				</div>
			</div>
		);
	}

	return (
		<div className="flex flex-col gap-4">
			<div>
				<Link
					to="/keys"
					search={{ tab: "relay", q: "" }}
					className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground transition-colors"
				>
					<ChevronLeft className="w-3.5 h-3.5" />
					Relay keys
				</Link>
				<h1 className="mt-2 text-xl font-semibold text-foreground">
					New relay key
				</h1>
				<p className="mt-1 text-xs text-muted-foreground">
					Issue a key for an app to call this relay. The secret is generated by
					the server and shown once after creation.
				</p>
			</div>
			<RelayKeyForm
				onSaved={(name) => setSavedName(name)}
				onCreated={(secret) => setPlaintext(secret)}
				onCancel={() =>
					void navigate({
						to: "/keys",
						search: { tab: "relay", q: "" },
					})
				}
			/>
		</div>
	);
}

function NewRelayKeyPage() {
	return (
		<Suspense fallback={<PageLoader />}>
			<NewRelayKeyInner />
		</Suspense>
	);
}
