/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSecretsRouteImport } from './routes/_authenticated/secrets'
import { Route as AuthenticatedRoutesRouteImport } from './routes/_authenticated/routes'
import { Route as AuthenticatedRatelimitsRouteImport } from './routes/_authenticated/ratelimits'
import { Route as AuthenticatedProvidersRouteImport } from './routes/_authenticated/providers'
import { Route as AuthenticatedPoolsRouteImport } from './routes/_authenticated/pools'
import { Route as AuthenticatedModelsRouteImport } from './routes/_authenticated/models'
import { Route as AuthenticatedBootstrapRouteImport } from './routes/_authenticated/bootstrap'
import { Route as AuthenticatedAttachmentsRouteImport } from './routes/_authenticated/attachments'
import { Route as AuthenticatedSecretsIndexRouteImport } from './routes/_authenticated/secrets.index'
import { Route as AuthenticatedRoutesIndexRouteImport } from './routes/_authenticated/routes.index'
import { Route as AuthenticatedRatelimitsIndexRouteImport } from './routes/_authenticated/ratelimits.index'
import { Route as AuthenticatedProvidersIndexRouteImport } from './routes/_authenticated/providers.index'
import { Route as AuthenticatedPoolsIndexRouteImport } from './routes/_authenticated/pools.index'
import { Route as AuthenticatedModelsIndexRouteImport } from './routes/_authenticated/models.index'
import { Route as AuthenticatedSecretsNewRouteImport } from './routes/_authenticated/secrets.new'
import { Route as AuthenticatedSecretsNameRouteImport } from './routes/_authenticated/secrets.$name'
import { Route as AuthenticatedRoutesNewRouteImport } from './routes/_authenticated/routes.new'
import { Route as AuthenticatedRoutesNameRouteImport } from './routes/_authenticated/routes.$name'
import { Route as AuthenticatedRatelimitsNewRouteImport } from './routes/_authenticated/ratelimits.new'
import { Route as AuthenticatedRatelimitsNameRouteImport } from './routes/_authenticated/ratelimits.$name'
import { Route as AuthenticatedProvidersNewRouteImport } from './routes/_authenticated/providers.new'
import { Route as AuthenticatedProvidersNameRouteImport } from './routes/_authenticated/providers.$name'
import { Route as AuthenticatedPoolsNewRouteImport } from './routes/_authenticated/pools.new'
import { Route as AuthenticatedPoolsNameRouteImport } from './routes/_authenticated/pools.$name'
import { Route as AuthenticatedModelsNewRouteImport } from './routes/_authenticated/models.new'
import { Route as AuthenticatedModelsNameRouteImport } from './routes/_authenticated/models.$name'
import { Route as AuthenticatedSecretsNameEditRouteImport } from './routes/_authenticated/secrets.$name.edit'
import { Route as AuthenticatedRoutesNameEditRouteImport } from './routes/_authenticated/routes.$name.edit'
import { Route as AuthenticatedRatelimitsNameEditRouteImport } from './routes/_authenticated/ratelimits.$name.edit'
import { Route as AuthenticatedProvidersNameEditRouteImport } from './routes/_authenticated/providers.$name.edit'
import { Route as AuthenticatedPoolsNameEditRouteImport } from './routes/_authenticated/pools.$name.edit'
import { Route as AuthenticatedModelsNameEditRouteImport } from './routes/_authenticated/models.$name.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecretsRoute = AuthenticatedSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoutesRoute = AuthenticatedRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRatelimitsRoute = AuthenticatedRatelimitsRouteImport.update({
  id: '/ratelimits',
  path: '/ratelimits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProvidersRoute = AuthenticatedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoolsRoute = AuthenticatedPoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBootstrapRoute = AuthenticatedBootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAttachmentsRoute =
  AuthenticatedAttachmentsRouteImport.update({
    id: '/attachments',
    path: '/attachments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSecretsIndexRoute =
  AuthenticatedSecretsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSecretsRoute,
  } as any)
const AuthenticatedRoutesIndexRoute =
  AuthenticatedRoutesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRoutesRoute,
  } as any)
const AuthenticatedRatelimitsIndexRoute =
  AuthenticatedRatelimitsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRatelimitsRoute,
  } as any)
const AuthenticatedProvidersIndexRoute =
  AuthenticatedProvidersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProvidersRoute,
  } as any)
const AuthenticatedPoolsIndexRoute = AuthenticatedPoolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPoolsRoute,
} as any)
const AuthenticatedModelsIndexRoute =
  AuthenticatedModelsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedModelsRoute,
  } as any)
const AuthenticatedSecretsNewRoute = AuthenticatedSecretsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedSecretsRoute,
} as any)
const AuthenticatedSecretsNameRoute =
  AuthenticatedSecretsNameRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => AuthenticatedSecretsRoute,
  } as any)
const AuthenticatedRoutesNewRoute = AuthenticatedRoutesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRoutesRoute,
} as any)
const AuthenticatedRoutesNameRoute = AuthenticatedRoutesNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AuthenticatedRoutesRoute,
} as any)
const AuthenticatedRatelimitsNewRoute =
  AuthenticatedRatelimitsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedRatelimitsRoute,
  } as any)
const AuthenticatedRatelimitsNameRoute =
  AuthenticatedRatelimitsNameRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => AuthenticatedRatelimitsRoute,
  } as any)
const AuthenticatedProvidersNewRoute =
  AuthenticatedProvidersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedProvidersRoute,
  } as any)
const AuthenticatedProvidersNameRoute =
  AuthenticatedProvidersNameRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => AuthenticatedProvidersRoute,
  } as any)
const AuthenticatedPoolsNewRoute = AuthenticatedPoolsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedPoolsRoute,
} as any)
const AuthenticatedPoolsNameRoute = AuthenticatedPoolsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AuthenticatedPoolsRoute,
} as any)
const AuthenticatedModelsNewRoute = AuthenticatedModelsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedModelsRoute,
} as any)
const AuthenticatedModelsNameRoute = AuthenticatedModelsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AuthenticatedModelsRoute,
} as any)
const AuthenticatedSecretsNameEditRoute =
  AuthenticatedSecretsNameEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedSecretsNameRoute,
  } as any)
const AuthenticatedRoutesNameEditRoute =
  AuthenticatedRoutesNameEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedRoutesNameRoute,
  } as any)
const AuthenticatedRatelimitsNameEditRoute =
  AuthenticatedRatelimitsNameEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedRatelimitsNameRoute,
  } as any)
const AuthenticatedProvidersNameEditRoute =
  AuthenticatedProvidersNameEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedProvidersNameRoute,
  } as any)
const AuthenticatedPoolsNameEditRoute =
  AuthenticatedPoolsNameEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedPoolsNameRoute,
  } as any)
const AuthenticatedModelsNameEditRoute =
  AuthenticatedModelsNameEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedModelsNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/attachments': typeof AuthenticatedAttachmentsRoute
  '/bootstrap': typeof AuthenticatedBootstrapRoute
  '/models': typeof AuthenticatedModelsRouteWithChildren
  '/pools': typeof AuthenticatedPoolsRouteWithChildren
  '/providers': typeof AuthenticatedProvidersRouteWithChildren
  '/ratelimits': typeof AuthenticatedRatelimitsRouteWithChildren
  '/routes': typeof AuthenticatedRoutesRouteWithChildren
  '/secrets': typeof AuthenticatedSecretsRouteWithChildren
  '/models/$name': typeof AuthenticatedModelsNameRouteWithChildren
  '/models/new': typeof AuthenticatedModelsNewRoute
  '/pools/$name': typeof AuthenticatedPoolsNameRouteWithChildren
  '/pools/new': typeof AuthenticatedPoolsNewRoute
  '/providers/$name': typeof AuthenticatedProvidersNameRouteWithChildren
  '/providers/new': typeof AuthenticatedProvidersNewRoute
  '/ratelimits/$name': typeof AuthenticatedRatelimitsNameRouteWithChildren
  '/ratelimits/new': typeof AuthenticatedRatelimitsNewRoute
  '/routes/$name': typeof AuthenticatedRoutesNameRouteWithChildren
  '/routes/new': typeof AuthenticatedRoutesNewRoute
  '/secrets/$name': typeof AuthenticatedSecretsNameRouteWithChildren
  '/secrets/new': typeof AuthenticatedSecretsNewRoute
  '/models/': typeof AuthenticatedModelsIndexRoute
  '/pools/': typeof AuthenticatedPoolsIndexRoute
  '/providers/': typeof AuthenticatedProvidersIndexRoute
  '/ratelimits/': typeof AuthenticatedRatelimitsIndexRoute
  '/routes/': typeof AuthenticatedRoutesIndexRoute
  '/secrets/': typeof AuthenticatedSecretsIndexRoute
  '/models/$name/edit': typeof AuthenticatedModelsNameEditRoute
  '/pools/$name/edit': typeof AuthenticatedPoolsNameEditRoute
  '/providers/$name/edit': typeof AuthenticatedProvidersNameEditRoute
  '/ratelimits/$name/edit': typeof AuthenticatedRatelimitsNameEditRoute
  '/routes/$name/edit': typeof AuthenticatedRoutesNameEditRoute
  '/secrets/$name/edit': typeof AuthenticatedSecretsNameEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/attachments': typeof AuthenticatedAttachmentsRoute
  '/bootstrap': typeof AuthenticatedBootstrapRoute
  '/': typeof AuthenticatedIndexRoute
  '/models/$name': typeof AuthenticatedModelsNameRouteWithChildren
  '/models/new': typeof AuthenticatedModelsNewRoute
  '/pools/$name': typeof AuthenticatedPoolsNameRouteWithChildren
  '/pools/new': typeof AuthenticatedPoolsNewRoute
  '/providers/$name': typeof AuthenticatedProvidersNameRouteWithChildren
  '/providers/new': typeof AuthenticatedProvidersNewRoute
  '/ratelimits/$name': typeof AuthenticatedRatelimitsNameRouteWithChildren
  '/ratelimits/new': typeof AuthenticatedRatelimitsNewRoute
  '/routes/$name': typeof AuthenticatedRoutesNameRouteWithChildren
  '/routes/new': typeof AuthenticatedRoutesNewRoute
  '/secrets/$name': typeof AuthenticatedSecretsNameRouteWithChildren
  '/secrets/new': typeof AuthenticatedSecretsNewRoute
  '/models': typeof AuthenticatedModelsIndexRoute
  '/pools': typeof AuthenticatedPoolsIndexRoute
  '/providers': typeof AuthenticatedProvidersIndexRoute
  '/ratelimits': typeof AuthenticatedRatelimitsIndexRoute
  '/routes': typeof AuthenticatedRoutesIndexRoute
  '/secrets': typeof AuthenticatedSecretsIndexRoute
  '/models/$name/edit': typeof AuthenticatedModelsNameEditRoute
  '/pools/$name/edit': typeof AuthenticatedPoolsNameEditRoute
  '/providers/$name/edit': typeof AuthenticatedProvidersNameEditRoute
  '/ratelimits/$name/edit': typeof AuthenticatedRatelimitsNameEditRoute
  '/routes/$name/edit': typeof AuthenticatedRoutesNameEditRoute
  '/secrets/$name/edit': typeof AuthenticatedSecretsNameEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/attachments': typeof AuthenticatedAttachmentsRoute
  '/_authenticated/bootstrap': typeof AuthenticatedBootstrapRoute
  '/_authenticated/models': typeof AuthenticatedModelsRouteWithChildren
  '/_authenticated/pools': typeof AuthenticatedPoolsRouteWithChildren
  '/_authenticated/providers': typeof AuthenticatedProvidersRouteWithChildren
  '/_authenticated/ratelimits': typeof AuthenticatedRatelimitsRouteWithChildren
  '/_authenticated/routes': typeof AuthenticatedRoutesRouteWithChildren
  '/_authenticated/secrets': typeof AuthenticatedSecretsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/models/$name': typeof AuthenticatedModelsNameRouteWithChildren
  '/_authenticated/models/new': typeof AuthenticatedModelsNewRoute
  '/_authenticated/pools/$name': typeof AuthenticatedPoolsNameRouteWithChildren
  '/_authenticated/pools/new': typeof AuthenticatedPoolsNewRoute
  '/_authenticated/providers/$name': typeof AuthenticatedProvidersNameRouteWithChildren
  '/_authenticated/providers/new': typeof AuthenticatedProvidersNewRoute
  '/_authenticated/ratelimits/$name': typeof AuthenticatedRatelimitsNameRouteWithChildren
  '/_authenticated/ratelimits/new': typeof AuthenticatedRatelimitsNewRoute
  '/_authenticated/routes/$name': typeof AuthenticatedRoutesNameRouteWithChildren
  '/_authenticated/routes/new': typeof AuthenticatedRoutesNewRoute
  '/_authenticated/secrets/$name': typeof AuthenticatedSecretsNameRouteWithChildren
  '/_authenticated/secrets/new': typeof AuthenticatedSecretsNewRoute
  '/_authenticated/models/': typeof AuthenticatedModelsIndexRoute
  '/_authenticated/pools/': typeof AuthenticatedPoolsIndexRoute
  '/_authenticated/providers/': typeof AuthenticatedProvidersIndexRoute
  '/_authenticated/ratelimits/': typeof AuthenticatedRatelimitsIndexRoute
  '/_authenticated/routes/': typeof AuthenticatedRoutesIndexRoute
  '/_authenticated/secrets/': typeof AuthenticatedSecretsIndexRoute
  '/_authenticated/models/$name/edit': typeof AuthenticatedModelsNameEditRoute
  '/_authenticated/pools/$name/edit': typeof AuthenticatedPoolsNameEditRoute
  '/_authenticated/providers/$name/edit': typeof AuthenticatedProvidersNameEditRoute
  '/_authenticated/ratelimits/$name/edit': typeof AuthenticatedRatelimitsNameEditRoute
  '/_authenticated/routes/$name/edit': typeof AuthenticatedRoutesNameEditRoute
  '/_authenticated/secrets/$name/edit': typeof AuthenticatedSecretsNameEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attachments'
    | '/bootstrap'
    | '/models'
    | '/pools'
    | '/providers'
    | '/ratelimits'
    | '/routes'
    | '/secrets'
    | '/models/$name'
    | '/models/new'
    | '/pools/$name'
    | '/pools/new'
    | '/providers/$name'
    | '/providers/new'
    | '/ratelimits/$name'
    | '/ratelimits/new'
    | '/routes/$name'
    | '/routes/new'
    | '/secrets/$name'
    | '/secrets/new'
    | '/models/'
    | '/pools/'
    | '/providers/'
    | '/ratelimits/'
    | '/routes/'
    | '/secrets/'
    | '/models/$name/edit'
    | '/pools/$name/edit'
    | '/providers/$name/edit'
    | '/ratelimits/$name/edit'
    | '/routes/$name/edit'
    | '/secrets/$name/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/attachments'
    | '/bootstrap'
    | '/'
    | '/models/$name'
    | '/models/new'
    | '/pools/$name'
    | '/pools/new'
    | '/providers/$name'
    | '/providers/new'
    | '/ratelimits/$name'
    | '/ratelimits/new'
    | '/routes/$name'
    | '/routes/new'
    | '/secrets/$name'
    | '/secrets/new'
    | '/models'
    | '/pools'
    | '/providers'
    | '/ratelimits'
    | '/routes'
    | '/secrets'
    | '/models/$name/edit'
    | '/pools/$name/edit'
    | '/providers/$name/edit'
    | '/ratelimits/$name/edit'
    | '/routes/$name/edit'
    | '/secrets/$name/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/attachments'
    | '/_authenticated/bootstrap'
    | '/_authenticated/models'
    | '/_authenticated/pools'
    | '/_authenticated/providers'
    | '/_authenticated/ratelimits'
    | '/_authenticated/routes'
    | '/_authenticated/secrets'
    | '/_authenticated/'
    | '/_authenticated/models/$name'
    | '/_authenticated/models/new'
    | '/_authenticated/pools/$name'
    | '/_authenticated/pools/new'
    | '/_authenticated/providers/$name'
    | '/_authenticated/providers/new'
    | '/_authenticated/ratelimits/$name'
    | '/_authenticated/ratelimits/new'
    | '/_authenticated/routes/$name'
    | '/_authenticated/routes/new'
    | '/_authenticated/secrets/$name'
    | '/_authenticated/secrets/new'
    | '/_authenticated/models/'
    | '/_authenticated/pools/'
    | '/_authenticated/providers/'
    | '/_authenticated/ratelimits/'
    | '/_authenticated/routes/'
    | '/_authenticated/secrets/'
    | '/_authenticated/models/$name/edit'
    | '/_authenticated/pools/$name/edit'
    | '/_authenticated/providers/$name/edit'
    | '/_authenticated/ratelimits/$name/edit'
    | '/_authenticated/routes/$name/edit'
    | '/_authenticated/secrets/$name/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/secrets': {
      id: '/_authenticated/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof AuthenticatedSecretsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routes': {
      id: '/_authenticated/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AuthenticatedRoutesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ratelimits': {
      id: '/_authenticated/ratelimits'
      path: '/ratelimits'
      fullPath: '/ratelimits'
      preLoaderRoute: typeof AuthenticatedRatelimitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/providers': {
      id: '/_authenticated/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthenticatedProvidersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pools': {
      id: '/_authenticated/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof AuthenticatedPoolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/models': {
      id: '/_authenticated/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bootstrap': {
      id: '/_authenticated/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof AuthenticatedBootstrapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attachments': {
      id: '/_authenticated/attachments'
      path: '/attachments'
      fullPath: '/attachments'
      preLoaderRoute: typeof AuthenticatedAttachmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/secrets/': {
      id: '/_authenticated/secrets/'
      path: '/'
      fullPath: '/secrets/'
      preLoaderRoute: typeof AuthenticatedSecretsIndexRouteImport
      parentRoute: typeof AuthenticatedSecretsRoute
    }
    '/_authenticated/routes/': {
      id: '/_authenticated/routes/'
      path: '/'
      fullPath: '/routes/'
      preLoaderRoute: typeof AuthenticatedRoutesIndexRouteImport
      parentRoute: typeof AuthenticatedRoutesRoute
    }
    '/_authenticated/ratelimits/': {
      id: '/_authenticated/ratelimits/'
      path: '/'
      fullPath: '/ratelimits/'
      preLoaderRoute: typeof AuthenticatedRatelimitsIndexRouteImport
      parentRoute: typeof AuthenticatedRatelimitsRoute
    }
    '/_authenticated/providers/': {
      id: '/_authenticated/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof AuthenticatedProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedProvidersRoute
    }
    '/_authenticated/pools/': {
      id: '/_authenticated/pools/'
      path: '/'
      fullPath: '/pools/'
      preLoaderRoute: typeof AuthenticatedPoolsIndexRouteImport
      parentRoute: typeof AuthenticatedPoolsRoute
    }
    '/_authenticated/models/': {
      id: '/_authenticated/models/'
      path: '/'
      fullPath: '/models/'
      preLoaderRoute: typeof AuthenticatedModelsIndexRouteImport
      parentRoute: typeof AuthenticatedModelsRoute
    }
    '/_authenticated/secrets/new': {
      id: '/_authenticated/secrets/new'
      path: '/new'
      fullPath: '/secrets/new'
      preLoaderRoute: typeof AuthenticatedSecretsNewRouteImport
      parentRoute: typeof AuthenticatedSecretsRoute
    }
    '/_authenticated/secrets/$name': {
      id: '/_authenticated/secrets/$name'
      path: '/$name'
      fullPath: '/secrets/$name'
      preLoaderRoute: typeof AuthenticatedSecretsNameRouteImport
      parentRoute: typeof AuthenticatedSecretsRoute
    }
    '/_authenticated/routes/new': {
      id: '/_authenticated/routes/new'
      path: '/new'
      fullPath: '/routes/new'
      preLoaderRoute: typeof AuthenticatedRoutesNewRouteImport
      parentRoute: typeof AuthenticatedRoutesRoute
    }
    '/_authenticated/routes/$name': {
      id: '/_authenticated/routes/$name'
      path: '/$name'
      fullPath: '/routes/$name'
      preLoaderRoute: typeof AuthenticatedRoutesNameRouteImport
      parentRoute: typeof AuthenticatedRoutesRoute
    }
    '/_authenticated/ratelimits/new': {
      id: '/_authenticated/ratelimits/new'
      path: '/new'
      fullPath: '/ratelimits/new'
      preLoaderRoute: typeof AuthenticatedRatelimitsNewRouteImport
      parentRoute: typeof AuthenticatedRatelimitsRoute
    }
    '/_authenticated/ratelimits/$name': {
      id: '/_authenticated/ratelimits/$name'
      path: '/$name'
      fullPath: '/ratelimits/$name'
      preLoaderRoute: typeof AuthenticatedRatelimitsNameRouteImport
      parentRoute: typeof AuthenticatedRatelimitsRoute
    }
    '/_authenticated/providers/new': {
      id: '/_authenticated/providers/new'
      path: '/new'
      fullPath: '/providers/new'
      preLoaderRoute: typeof AuthenticatedProvidersNewRouteImport
      parentRoute: typeof AuthenticatedProvidersRoute
    }
    '/_authenticated/providers/$name': {
      id: '/_authenticated/providers/$name'
      path: '/$name'
      fullPath: '/providers/$name'
      preLoaderRoute: typeof AuthenticatedProvidersNameRouteImport
      parentRoute: typeof AuthenticatedProvidersRoute
    }
    '/_authenticated/pools/new': {
      id: '/_authenticated/pools/new'
      path: '/new'
      fullPath: '/pools/new'
      preLoaderRoute: typeof AuthenticatedPoolsNewRouteImport
      parentRoute: typeof AuthenticatedPoolsRoute
    }
    '/_authenticated/pools/$name': {
      id: '/_authenticated/pools/$name'
      path: '/$name'
      fullPath: '/pools/$name'
      preLoaderRoute: typeof AuthenticatedPoolsNameRouteImport
      parentRoute: typeof AuthenticatedPoolsRoute
    }
    '/_authenticated/models/new': {
      id: '/_authenticated/models/new'
      path: '/new'
      fullPath: '/models/new'
      preLoaderRoute: typeof AuthenticatedModelsNewRouteImport
      parentRoute: typeof AuthenticatedModelsRoute
    }
    '/_authenticated/models/$name': {
      id: '/_authenticated/models/$name'
      path: '/$name'
      fullPath: '/models/$name'
      preLoaderRoute: typeof AuthenticatedModelsNameRouteImport
      parentRoute: typeof AuthenticatedModelsRoute
    }
    '/_authenticated/secrets/$name/edit': {
      id: '/_authenticated/secrets/$name/edit'
      path: '/edit'
      fullPath: '/secrets/$name/edit'
      preLoaderRoute: typeof AuthenticatedSecretsNameEditRouteImport
      parentRoute: typeof AuthenticatedSecretsNameRoute
    }
    '/_authenticated/routes/$name/edit': {
      id: '/_authenticated/routes/$name/edit'
      path: '/edit'
      fullPath: '/routes/$name/edit'
      preLoaderRoute: typeof AuthenticatedRoutesNameEditRouteImport
      parentRoute: typeof AuthenticatedRoutesNameRoute
    }
    '/_authenticated/ratelimits/$name/edit': {
      id: '/_authenticated/ratelimits/$name/edit'
      path: '/edit'
      fullPath: '/ratelimits/$name/edit'
      preLoaderRoute: typeof AuthenticatedRatelimitsNameEditRouteImport
      parentRoute: typeof AuthenticatedRatelimitsNameRoute
    }
    '/_authenticated/providers/$name/edit': {
      id: '/_authenticated/providers/$name/edit'
      path: '/edit'
      fullPath: '/providers/$name/edit'
      preLoaderRoute: typeof AuthenticatedProvidersNameEditRouteImport
      parentRoute: typeof AuthenticatedProvidersNameRoute
    }
    '/_authenticated/pools/$name/edit': {
      id: '/_authenticated/pools/$name/edit'
      path: '/edit'
      fullPath: '/pools/$name/edit'
      preLoaderRoute: typeof AuthenticatedPoolsNameEditRouteImport
      parentRoute: typeof AuthenticatedPoolsNameRoute
    }
    '/_authenticated/models/$name/edit': {
      id: '/_authenticated/models/$name/edit'
      path: '/edit'
      fullPath: '/models/$name/edit'
      preLoaderRoute: typeof AuthenticatedModelsNameEditRouteImport
      parentRoute: typeof AuthenticatedModelsNameRoute
    }
  }
}

interface AuthenticatedModelsNameRouteChildren {
  AuthenticatedModelsNameEditRoute: typeof AuthenticatedModelsNameEditRoute
}

const AuthenticatedModelsNameRouteChildren: AuthenticatedModelsNameRouteChildren =
  {
    AuthenticatedModelsNameEditRoute: AuthenticatedModelsNameEditRoute,
  }

const AuthenticatedModelsNameRouteWithChildren =
  AuthenticatedModelsNameRoute._addFileChildren(
    AuthenticatedModelsNameRouteChildren,
  )

interface AuthenticatedModelsRouteChildren {
  AuthenticatedModelsNameRoute: typeof AuthenticatedModelsNameRouteWithChildren
  AuthenticatedModelsNewRoute: typeof AuthenticatedModelsNewRoute
  AuthenticatedModelsIndexRoute: typeof AuthenticatedModelsIndexRoute
}

const AuthenticatedModelsRouteChildren: AuthenticatedModelsRouteChildren = {
  AuthenticatedModelsNameRoute: AuthenticatedModelsNameRouteWithChildren,
  AuthenticatedModelsNewRoute: AuthenticatedModelsNewRoute,
  AuthenticatedModelsIndexRoute: AuthenticatedModelsIndexRoute,
}

const AuthenticatedModelsRouteWithChildren =
  AuthenticatedModelsRoute._addFileChildren(AuthenticatedModelsRouteChildren)

interface AuthenticatedPoolsNameRouteChildren {
  AuthenticatedPoolsNameEditRoute: typeof AuthenticatedPoolsNameEditRoute
}

const AuthenticatedPoolsNameRouteChildren: AuthenticatedPoolsNameRouteChildren =
  {
    AuthenticatedPoolsNameEditRoute: AuthenticatedPoolsNameEditRoute,
  }

const AuthenticatedPoolsNameRouteWithChildren =
  AuthenticatedPoolsNameRoute._addFileChildren(
    AuthenticatedPoolsNameRouteChildren,
  )

interface AuthenticatedPoolsRouteChildren {
  AuthenticatedPoolsNameRoute: typeof AuthenticatedPoolsNameRouteWithChildren
  AuthenticatedPoolsNewRoute: typeof AuthenticatedPoolsNewRoute
  AuthenticatedPoolsIndexRoute: typeof AuthenticatedPoolsIndexRoute
}

const AuthenticatedPoolsRouteChildren: AuthenticatedPoolsRouteChildren = {
  AuthenticatedPoolsNameRoute: AuthenticatedPoolsNameRouteWithChildren,
  AuthenticatedPoolsNewRoute: AuthenticatedPoolsNewRoute,
  AuthenticatedPoolsIndexRoute: AuthenticatedPoolsIndexRoute,
}

const AuthenticatedPoolsRouteWithChildren =
  AuthenticatedPoolsRoute._addFileChildren(AuthenticatedPoolsRouteChildren)

interface AuthenticatedProvidersNameRouteChildren {
  AuthenticatedProvidersNameEditRoute: typeof AuthenticatedProvidersNameEditRoute
}

const AuthenticatedProvidersNameRouteChildren: AuthenticatedProvidersNameRouteChildren =
  {
    AuthenticatedProvidersNameEditRoute: AuthenticatedProvidersNameEditRoute,
  }

const AuthenticatedProvidersNameRouteWithChildren =
  AuthenticatedProvidersNameRoute._addFileChildren(
    AuthenticatedProvidersNameRouteChildren,
  )

interface AuthenticatedProvidersRouteChildren {
  AuthenticatedProvidersNameRoute: typeof AuthenticatedProvidersNameRouteWithChildren
  AuthenticatedProvidersNewRoute: typeof AuthenticatedProvidersNewRoute
  AuthenticatedProvidersIndexRoute: typeof AuthenticatedProvidersIndexRoute
}

const AuthenticatedProvidersRouteChildren: AuthenticatedProvidersRouteChildren =
  {
    AuthenticatedProvidersNameRoute:
      AuthenticatedProvidersNameRouteWithChildren,
    AuthenticatedProvidersNewRoute: AuthenticatedProvidersNewRoute,
    AuthenticatedProvidersIndexRoute: AuthenticatedProvidersIndexRoute,
  }

const AuthenticatedProvidersRouteWithChildren =
  AuthenticatedProvidersRoute._addFileChildren(
    AuthenticatedProvidersRouteChildren,
  )

interface AuthenticatedRatelimitsNameRouteChildren {
  AuthenticatedRatelimitsNameEditRoute: typeof AuthenticatedRatelimitsNameEditRoute
}

const AuthenticatedRatelimitsNameRouteChildren: AuthenticatedRatelimitsNameRouteChildren =
  {
    AuthenticatedRatelimitsNameEditRoute: AuthenticatedRatelimitsNameEditRoute,
  }

const AuthenticatedRatelimitsNameRouteWithChildren =
  AuthenticatedRatelimitsNameRoute._addFileChildren(
    AuthenticatedRatelimitsNameRouteChildren,
  )

interface AuthenticatedRatelimitsRouteChildren {
  AuthenticatedRatelimitsNameRoute: typeof AuthenticatedRatelimitsNameRouteWithChildren
  AuthenticatedRatelimitsNewRoute: typeof AuthenticatedRatelimitsNewRoute
  AuthenticatedRatelimitsIndexRoute: typeof AuthenticatedRatelimitsIndexRoute
}

const AuthenticatedRatelimitsRouteChildren: AuthenticatedRatelimitsRouteChildren =
  {
    AuthenticatedRatelimitsNameRoute:
      AuthenticatedRatelimitsNameRouteWithChildren,
    AuthenticatedRatelimitsNewRoute: AuthenticatedRatelimitsNewRoute,
    AuthenticatedRatelimitsIndexRoute: AuthenticatedRatelimitsIndexRoute,
  }

const AuthenticatedRatelimitsRouteWithChildren =
  AuthenticatedRatelimitsRoute._addFileChildren(
    AuthenticatedRatelimitsRouteChildren,
  )

interface AuthenticatedRoutesNameRouteChildren {
  AuthenticatedRoutesNameEditRoute: typeof AuthenticatedRoutesNameEditRoute
}

const AuthenticatedRoutesNameRouteChildren: AuthenticatedRoutesNameRouteChildren =
  {
    AuthenticatedRoutesNameEditRoute: AuthenticatedRoutesNameEditRoute,
  }

const AuthenticatedRoutesNameRouteWithChildren =
  AuthenticatedRoutesNameRoute._addFileChildren(
    AuthenticatedRoutesNameRouteChildren,
  )

interface AuthenticatedRoutesRouteChildren {
  AuthenticatedRoutesNameRoute: typeof AuthenticatedRoutesNameRouteWithChildren
  AuthenticatedRoutesNewRoute: typeof AuthenticatedRoutesNewRoute
  AuthenticatedRoutesIndexRoute: typeof AuthenticatedRoutesIndexRoute
}

const AuthenticatedRoutesRouteChildren: AuthenticatedRoutesRouteChildren = {
  AuthenticatedRoutesNameRoute: AuthenticatedRoutesNameRouteWithChildren,
  AuthenticatedRoutesNewRoute: AuthenticatedRoutesNewRoute,
  AuthenticatedRoutesIndexRoute: AuthenticatedRoutesIndexRoute,
}

const AuthenticatedRoutesRouteWithChildren =
  AuthenticatedRoutesRoute._addFileChildren(AuthenticatedRoutesRouteChildren)

interface AuthenticatedSecretsNameRouteChildren {
  AuthenticatedSecretsNameEditRoute: typeof AuthenticatedSecretsNameEditRoute
}

const AuthenticatedSecretsNameRouteChildren: AuthenticatedSecretsNameRouteChildren =
  {
    AuthenticatedSecretsNameEditRoute: AuthenticatedSecretsNameEditRoute,
  }

const AuthenticatedSecretsNameRouteWithChildren =
  AuthenticatedSecretsNameRoute._addFileChildren(
    AuthenticatedSecretsNameRouteChildren,
  )

interface AuthenticatedSecretsRouteChildren {
  AuthenticatedSecretsNameRoute: typeof AuthenticatedSecretsNameRouteWithChildren
  AuthenticatedSecretsNewRoute: typeof AuthenticatedSecretsNewRoute
  AuthenticatedSecretsIndexRoute: typeof AuthenticatedSecretsIndexRoute
}

const AuthenticatedSecretsRouteChildren: AuthenticatedSecretsRouteChildren = {
  AuthenticatedSecretsNameRoute: AuthenticatedSecretsNameRouteWithChildren,
  AuthenticatedSecretsNewRoute: AuthenticatedSecretsNewRoute,
  AuthenticatedSecretsIndexRoute: AuthenticatedSecretsIndexRoute,
}

const AuthenticatedSecretsRouteWithChildren =
  AuthenticatedSecretsRoute._addFileChildren(AuthenticatedSecretsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAttachmentsRoute: typeof AuthenticatedAttachmentsRoute
  AuthenticatedBootstrapRoute: typeof AuthenticatedBootstrapRoute
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRouteWithChildren
  AuthenticatedPoolsRoute: typeof AuthenticatedPoolsRouteWithChildren
  AuthenticatedProvidersRoute: typeof AuthenticatedProvidersRouteWithChildren
  AuthenticatedRatelimitsRoute: typeof AuthenticatedRatelimitsRouteWithChildren
  AuthenticatedRoutesRoute: typeof AuthenticatedRoutesRouteWithChildren
  AuthenticatedSecretsRoute: typeof AuthenticatedSecretsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAttachmentsRoute: AuthenticatedAttachmentsRoute,
  AuthenticatedBootstrapRoute: AuthenticatedBootstrapRoute,
  AuthenticatedModelsRoute: AuthenticatedModelsRouteWithChildren,
  AuthenticatedPoolsRoute: AuthenticatedPoolsRouteWithChildren,
  AuthenticatedProvidersRoute: AuthenticatedProvidersRouteWithChildren,
  AuthenticatedRatelimitsRoute: AuthenticatedRatelimitsRouteWithChildren,
  AuthenticatedRoutesRoute: AuthenticatedRoutesRouteWithChildren,
  AuthenticatedSecretsRoute: AuthenticatedSecretsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
