/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsageRouteImport } from './routes/_authenticated/usage'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSecretsRouteImport } from './routes/_authenticated/secrets'
import { Route as AuthenticatedRoutesRouteImport } from './routes/_authenticated/routes'
import { Route as AuthenticatedRoutersRouteImport } from './routes/_authenticated/routers'
import { Route as AuthenticatedRatelimitsRouteImport } from './routes/_authenticated/ratelimits'
import { Route as AuthenticatedProvidersRouteImport } from './routes/_authenticated/providers'
import { Route as AuthenticatedPoolsRouteImport } from './routes/_authenticated/pools'
import { Route as AuthenticatedPoliciesRouteImport } from './routes/_authenticated/policies'
import { Route as AuthenticatedModelsRouteImport } from './routes/_authenticated/models'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedKeysRouteImport } from './routes/_authenticated/keys'
import { Route as AuthenticatedBootstrapRouteImport } from './routes/_authenticated/bootstrap'
import { Route as AuthenticatedAttachmentsRouteImport } from './routes/_authenticated/attachments'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedSecretsIndexRouteImport } from './routes/_authenticated/secrets.index'
import { Route as AuthenticatedRoutesIndexRouteImport } from './routes/_authenticated/routes.index'
import { Route as AuthenticatedRatelimitsIndexRouteImport } from './routes/_authenticated/ratelimits.index'
import { Route as AuthenticatedProvidersIndexRouteImport } from './routes/_authenticated/providers.index'
import { Route as AuthenticatedPoolsIndexRouteImport } from './routes/_authenticated/pools.index'
import { Route as AuthenticatedPoliciesIndexRouteImport } from './routes/_authenticated/policies.index'
import { Route as AuthenticatedModelsIndexRouteImport } from './routes/_authenticated/models.index'
import { Route as AuthenticatedSettingsPassthroughRouteImport } from './routes/_authenticated/settings.passthrough'
import { Route as AuthenticatedSecretsNewRouteImport } from './routes/_authenticated/secrets.new'
import { Route as AuthenticatedSecretsNameRouteImport } from './routes/_authenticated/secrets.$name'
import { Route as AuthenticatedRoutesNewRouteImport } from './routes/_authenticated/routes.new'
import { Route as AuthenticatedRoutesNameRouteImport } from './routes/_authenticated/routes.$name'
import { Route as AuthenticatedRatelimitsNameRouteImport } from './routes/_authenticated/ratelimits.$name'
import { Route as AuthenticatedProvidersNewRouteImport } from './routes/_authenticated/providers.new'
import { Route as AuthenticatedProvidersNameRouteImport } from './routes/_authenticated/providers.$name'
import { Route as AuthenticatedPoolsNameRouteImport } from './routes/_authenticated/pools.$name'
import { Route as AuthenticatedPoliciesNewRouteImport } from './routes/_authenticated/policies.new'
import { Route as AuthenticatedPoliciesNameRouteImport } from './routes/_authenticated/policies.$name'
import { Route as AuthenticatedModelsNewRouteImport } from './routes/_authenticated/models.new'
import { Route as AuthenticatedModelsNameRouteImport } from './routes/_authenticated/models.$name'
import { Route as AuthenticatedKeysIdRouteImport } from './routes/_authenticated/keys.$id'
import { Route as AuthenticatedSecretsNameEditRouteImport } from './routes/_authenticated/secrets.$name.edit'
import { Route as AuthenticatedRoutesNameEditRouteImport } from './routes/_authenticated/routes.$name.edit'
import { Route as AuthenticatedProvidersNameEditRouteImport } from './routes/_authenticated/providers.$name.edit'
import { Route as AuthenticatedPoliciesRateLimitsNewRouteImport } from './routes/_authenticated/policies.rate-limits.new'
import { Route as AuthenticatedPoliciesRateLimitsNameRouteImport } from './routes/_authenticated/policies.rate-limits.$name'
import { Route as AuthenticatedModelsNameEditRouteImport } from './routes/_authenticated/models.$name.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecretsRoute = AuthenticatedSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoutesRoute = AuthenticatedRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoutersRoute = AuthenticatedRoutersRouteImport.update({
  id: '/routers',
  path: '/routers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRatelimitsRoute = AuthenticatedRatelimitsRouteImport.update({
  id: '/ratelimits',
  path: '/ratelimits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProvidersRoute = AuthenticatedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoolsRoute = AuthenticatedPoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoliciesRoute = AuthenticatedPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKeysRoute = AuthenticatedKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBootstrapRoute = AuthenticatedBootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAttachmentsRoute =
  AuthenticatedAttachmentsRouteImport.update({
    id: '/attachments',
    path: '/attachments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSecretsIndexRoute =
  AuthenticatedSecretsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSecretsRoute,
  } as any)
const AuthenticatedRoutesIndexRoute =
  AuthenticatedRoutesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRoutesRoute,
  } as any)
const AuthenticatedRatelimitsIndexRoute =
  AuthenticatedRatelimitsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRatelimitsRoute,
  } as any)
const AuthenticatedProvidersIndexRoute =
  AuthenticatedProvidersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProvidersRoute,
  } as any)
const AuthenticatedPoolsIndexRoute = AuthenticatedPoolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPoolsRoute,
} as any)
const AuthenticatedPoliciesIndexRoute =
  AuthenticatedPoliciesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedModelsIndexRoute =
  AuthenticatedModelsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedModelsRoute,
  } as any)
const AuthenticatedSettingsPassthroughRoute =
  AuthenticatedSettingsPassthroughRouteImport.update({
    id: '/passthrough',
    path: '/passthrough',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSecretsNewRoute = AuthenticatedSecretsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedSecretsRoute,
} as any)
const AuthenticatedSecretsNameRoute =
  AuthenticatedSecretsNameRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => AuthenticatedSecretsRoute,
  } as any)
const AuthenticatedRoutesNewRoute = AuthenticatedRoutesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRoutesRoute,
} as any)
const AuthenticatedRoutesNameRoute = AuthenticatedRoutesNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AuthenticatedRoutesRoute,
} as any)
const AuthenticatedRatelimitsNameRoute =
  AuthenticatedRatelimitsNameRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => AuthenticatedRatelimitsRoute,
  } as any)
const AuthenticatedProvidersNewRoute =
  AuthenticatedProvidersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedProvidersRoute,
  } as any)
const AuthenticatedProvidersNameRoute =
  AuthenticatedProvidersNameRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => AuthenticatedProvidersRoute,
  } as any)
const AuthenticatedPoolsNameRoute = AuthenticatedPoolsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AuthenticatedPoolsRoute,
} as any)
const AuthenticatedPoliciesNewRoute =
  AuthenticatedPoliciesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedPoliciesNameRoute =
  AuthenticatedPoliciesNameRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedModelsNewRoute = AuthenticatedModelsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedModelsRoute,
} as any)
const AuthenticatedModelsNameRoute = AuthenticatedModelsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AuthenticatedModelsRoute,
} as any)
const AuthenticatedKeysIdRoute = AuthenticatedKeysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedKeysRoute,
} as any)
const AuthenticatedSecretsNameEditRoute =
  AuthenticatedSecretsNameEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedSecretsNameRoute,
  } as any)
const AuthenticatedRoutesNameEditRoute =
  AuthenticatedRoutesNameEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedRoutesNameRoute,
  } as any)
const AuthenticatedProvidersNameEditRoute =
  AuthenticatedProvidersNameEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedProvidersNameRoute,
  } as any)
const AuthenticatedPoliciesRateLimitsNewRoute =
  AuthenticatedPoliciesRateLimitsNewRouteImport.update({
    id: '/rate-limits/new',
    path: '/rate-limits/new',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedPoliciesRateLimitsNameRoute =
  AuthenticatedPoliciesRateLimitsNameRouteImport.update({
    id: '/rate-limits/$name',
    path: '/rate-limits/$name',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedModelsNameEditRoute =
  AuthenticatedModelsNameEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedModelsNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/attachments': typeof AuthenticatedAttachmentsRoute
  '/bootstrap': typeof AuthenticatedBootstrapRoute
  '/keys': typeof AuthenticatedKeysRouteWithChildren
  '/logs': typeof AuthenticatedLogsRoute
  '/models': typeof AuthenticatedModelsRouteWithChildren
  '/policies': typeof AuthenticatedPoliciesRouteWithChildren
  '/pools': typeof AuthenticatedPoolsRouteWithChildren
  '/providers': typeof AuthenticatedProvidersRouteWithChildren
  '/ratelimits': typeof AuthenticatedRatelimitsRouteWithChildren
  '/routers': typeof AuthenticatedRoutersRoute
  '/routes': typeof AuthenticatedRoutesRouteWithChildren
  '/secrets': typeof AuthenticatedSecretsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/usage': typeof AuthenticatedUsageRoute
  '/keys/$id': typeof AuthenticatedKeysIdRoute
  '/models/$name': typeof AuthenticatedModelsNameRouteWithChildren
  '/models/new': typeof AuthenticatedModelsNewRoute
  '/policies/$name': typeof AuthenticatedPoliciesNameRoute
  '/policies/new': typeof AuthenticatedPoliciesNewRoute
  '/pools/$name': typeof AuthenticatedPoolsNameRoute
  '/providers/$name': typeof AuthenticatedProvidersNameRouteWithChildren
  '/providers/new': typeof AuthenticatedProvidersNewRoute
  '/ratelimits/$name': typeof AuthenticatedRatelimitsNameRoute
  '/routes/$name': typeof AuthenticatedRoutesNameRouteWithChildren
  '/routes/new': typeof AuthenticatedRoutesNewRoute
  '/secrets/$name': typeof AuthenticatedSecretsNameRouteWithChildren
  '/secrets/new': typeof AuthenticatedSecretsNewRoute
  '/settings/passthrough': typeof AuthenticatedSettingsPassthroughRoute
  '/models/': typeof AuthenticatedModelsIndexRoute
  '/policies/': typeof AuthenticatedPoliciesIndexRoute
  '/pools/': typeof AuthenticatedPoolsIndexRoute
  '/providers/': typeof AuthenticatedProvidersIndexRoute
  '/ratelimits/': typeof AuthenticatedRatelimitsIndexRoute
  '/routes/': typeof AuthenticatedRoutesIndexRoute
  '/secrets/': typeof AuthenticatedSecretsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/models/$name/edit': typeof AuthenticatedModelsNameEditRoute
  '/policies/rate-limits/$name': typeof AuthenticatedPoliciesRateLimitsNameRoute
  '/policies/rate-limits/new': typeof AuthenticatedPoliciesRateLimitsNewRoute
  '/providers/$name/edit': typeof AuthenticatedProvidersNameEditRoute
  '/routes/$name/edit': typeof AuthenticatedRoutesNameEditRoute
  '/secrets/$name/edit': typeof AuthenticatedSecretsNameEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/attachments': typeof AuthenticatedAttachmentsRoute
  '/bootstrap': typeof AuthenticatedBootstrapRoute
  '/keys': typeof AuthenticatedKeysRouteWithChildren
  '/logs': typeof AuthenticatedLogsRoute
  '/routers': typeof AuthenticatedRoutersRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/': typeof AuthenticatedIndexRoute
  '/keys/$id': typeof AuthenticatedKeysIdRoute
  '/models/$name': typeof AuthenticatedModelsNameRouteWithChildren
  '/models/new': typeof AuthenticatedModelsNewRoute
  '/policies/$name': typeof AuthenticatedPoliciesNameRoute
  '/policies/new': typeof AuthenticatedPoliciesNewRoute
  '/pools/$name': typeof AuthenticatedPoolsNameRoute
  '/providers/$name': typeof AuthenticatedProvidersNameRouteWithChildren
  '/providers/new': typeof AuthenticatedProvidersNewRoute
  '/ratelimits/$name': typeof AuthenticatedRatelimitsNameRoute
  '/routes/$name': typeof AuthenticatedRoutesNameRouteWithChildren
  '/routes/new': typeof AuthenticatedRoutesNewRoute
  '/secrets/$name': typeof AuthenticatedSecretsNameRouteWithChildren
  '/secrets/new': typeof AuthenticatedSecretsNewRoute
  '/settings/passthrough': typeof AuthenticatedSettingsPassthroughRoute
  '/models': typeof AuthenticatedModelsIndexRoute
  '/policies': typeof AuthenticatedPoliciesIndexRoute
  '/pools': typeof AuthenticatedPoolsIndexRoute
  '/providers': typeof AuthenticatedProvidersIndexRoute
  '/ratelimits': typeof AuthenticatedRatelimitsIndexRoute
  '/routes': typeof AuthenticatedRoutesIndexRoute
  '/secrets': typeof AuthenticatedSecretsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/models/$name/edit': typeof AuthenticatedModelsNameEditRoute
  '/policies/rate-limits/$name': typeof AuthenticatedPoliciesRateLimitsNameRoute
  '/policies/rate-limits/new': typeof AuthenticatedPoliciesRateLimitsNewRoute
  '/providers/$name/edit': typeof AuthenticatedProvidersNameEditRoute
  '/routes/$name/edit': typeof AuthenticatedRoutesNameEditRoute
  '/secrets/$name/edit': typeof AuthenticatedSecretsNameEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/attachments': typeof AuthenticatedAttachmentsRoute
  '/_authenticated/bootstrap': typeof AuthenticatedBootstrapRoute
  '/_authenticated/keys': typeof AuthenticatedKeysRouteWithChildren
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/models': typeof AuthenticatedModelsRouteWithChildren
  '/_authenticated/policies': typeof AuthenticatedPoliciesRouteWithChildren
  '/_authenticated/pools': typeof AuthenticatedPoolsRouteWithChildren
  '/_authenticated/providers': typeof AuthenticatedProvidersRouteWithChildren
  '/_authenticated/ratelimits': typeof AuthenticatedRatelimitsRouteWithChildren
  '/_authenticated/routers': typeof AuthenticatedRoutersRoute
  '/_authenticated/routes': typeof AuthenticatedRoutesRouteWithChildren
  '/_authenticated/secrets': typeof AuthenticatedSecretsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/usage': typeof AuthenticatedUsageRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/keys/$id': typeof AuthenticatedKeysIdRoute
  '/_authenticated/models/$name': typeof AuthenticatedModelsNameRouteWithChildren
  '/_authenticated/models/new': typeof AuthenticatedModelsNewRoute
  '/_authenticated/policies/$name': typeof AuthenticatedPoliciesNameRoute
  '/_authenticated/policies/new': typeof AuthenticatedPoliciesNewRoute
  '/_authenticated/pools/$name': typeof AuthenticatedPoolsNameRoute
  '/_authenticated/providers/$name': typeof AuthenticatedProvidersNameRouteWithChildren
  '/_authenticated/providers/new': typeof AuthenticatedProvidersNewRoute
  '/_authenticated/ratelimits/$name': typeof AuthenticatedRatelimitsNameRoute
  '/_authenticated/routes/$name': typeof AuthenticatedRoutesNameRouteWithChildren
  '/_authenticated/routes/new': typeof AuthenticatedRoutesNewRoute
  '/_authenticated/secrets/$name': typeof AuthenticatedSecretsNameRouteWithChildren
  '/_authenticated/secrets/new': typeof AuthenticatedSecretsNewRoute
  '/_authenticated/settings/passthrough': typeof AuthenticatedSettingsPassthroughRoute
  '/_authenticated/models/': typeof AuthenticatedModelsIndexRoute
  '/_authenticated/policies/': typeof AuthenticatedPoliciesIndexRoute
  '/_authenticated/pools/': typeof AuthenticatedPoolsIndexRoute
  '/_authenticated/providers/': typeof AuthenticatedProvidersIndexRoute
  '/_authenticated/ratelimits/': typeof AuthenticatedRatelimitsIndexRoute
  '/_authenticated/routes/': typeof AuthenticatedRoutesIndexRoute
  '/_authenticated/secrets/': typeof AuthenticatedSecretsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/models/$name/edit': typeof AuthenticatedModelsNameEditRoute
  '/_authenticated/policies/rate-limits/$name': typeof AuthenticatedPoliciesRateLimitsNameRoute
  '/_authenticated/policies/rate-limits/new': typeof AuthenticatedPoliciesRateLimitsNewRoute
  '/_authenticated/providers/$name/edit': typeof AuthenticatedProvidersNameEditRoute
  '/_authenticated/routes/$name/edit': typeof AuthenticatedRoutesNameEditRoute
  '/_authenticated/secrets/$name/edit': typeof AuthenticatedSecretsNameEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attachments'
    | '/bootstrap'
    | '/keys'
    | '/logs'
    | '/models'
    | '/policies'
    | '/pools'
    | '/providers'
    | '/ratelimits'
    | '/routers'
    | '/routes'
    | '/secrets'
    | '/settings'
    | '/usage'
    | '/keys/$id'
    | '/models/$name'
    | '/models/new'
    | '/policies/$name'
    | '/policies/new'
    | '/pools/$name'
    | '/providers/$name'
    | '/providers/new'
    | '/ratelimits/$name'
    | '/routes/$name'
    | '/routes/new'
    | '/secrets/$name'
    | '/secrets/new'
    | '/settings/passthrough'
    | '/models/'
    | '/policies/'
    | '/pools/'
    | '/providers/'
    | '/ratelimits/'
    | '/routes/'
    | '/secrets/'
    | '/settings/'
    | '/models/$name/edit'
    | '/policies/rate-limits/$name'
    | '/policies/rate-limits/new'
    | '/providers/$name/edit'
    | '/routes/$name/edit'
    | '/secrets/$name/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/attachments'
    | '/bootstrap'
    | '/keys'
    | '/logs'
    | '/routers'
    | '/usage'
    | '/'
    | '/keys/$id'
    | '/models/$name'
    | '/models/new'
    | '/policies/$name'
    | '/policies/new'
    | '/pools/$name'
    | '/providers/$name'
    | '/providers/new'
    | '/ratelimits/$name'
    | '/routes/$name'
    | '/routes/new'
    | '/secrets/$name'
    | '/secrets/new'
    | '/settings/passthrough'
    | '/models'
    | '/policies'
    | '/pools'
    | '/providers'
    | '/ratelimits'
    | '/routes'
    | '/secrets'
    | '/settings'
    | '/models/$name/edit'
    | '/policies/rate-limits/$name'
    | '/policies/rate-limits/new'
    | '/providers/$name/edit'
    | '/routes/$name/edit'
    | '/secrets/$name/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/attachments'
    | '/_authenticated/bootstrap'
    | '/_authenticated/keys'
    | '/_authenticated/logs'
    | '/_authenticated/models'
    | '/_authenticated/policies'
    | '/_authenticated/pools'
    | '/_authenticated/providers'
    | '/_authenticated/ratelimits'
    | '/_authenticated/routers'
    | '/_authenticated/routes'
    | '/_authenticated/secrets'
    | '/_authenticated/settings'
    | '/_authenticated/usage'
    | '/_authenticated/'
    | '/_authenticated/keys/$id'
    | '/_authenticated/models/$name'
    | '/_authenticated/models/new'
    | '/_authenticated/policies/$name'
    | '/_authenticated/policies/new'
    | '/_authenticated/pools/$name'
    | '/_authenticated/providers/$name'
    | '/_authenticated/providers/new'
    | '/_authenticated/ratelimits/$name'
    | '/_authenticated/routes/$name'
    | '/_authenticated/routes/new'
    | '/_authenticated/secrets/$name'
    | '/_authenticated/secrets/new'
    | '/_authenticated/settings/passthrough'
    | '/_authenticated/models/'
    | '/_authenticated/policies/'
    | '/_authenticated/pools/'
    | '/_authenticated/providers/'
    | '/_authenticated/ratelimits/'
    | '/_authenticated/routes/'
    | '/_authenticated/secrets/'
    | '/_authenticated/settings/'
    | '/_authenticated/models/$name/edit'
    | '/_authenticated/policies/rate-limits/$name'
    | '/_authenticated/policies/rate-limits/new'
    | '/_authenticated/providers/$name/edit'
    | '/_authenticated/routes/$name/edit'
    | '/_authenticated/secrets/$name/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usage': {
      id: '/_authenticated/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/secrets': {
      id: '/_authenticated/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof AuthenticatedSecretsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routes': {
      id: '/_authenticated/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AuthenticatedRoutesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routers': {
      id: '/_authenticated/routers'
      path: '/routers'
      fullPath: '/routers'
      preLoaderRoute: typeof AuthenticatedRoutersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ratelimits': {
      id: '/_authenticated/ratelimits'
      path: '/ratelimits'
      fullPath: '/ratelimits'
      preLoaderRoute: typeof AuthenticatedRatelimitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/providers': {
      id: '/_authenticated/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthenticatedProvidersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pools': {
      id: '/_authenticated/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof AuthenticatedPoolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/policies': {
      id: '/_authenticated/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthenticatedPoliciesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/models': {
      id: '/_authenticated/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/keys': {
      id: '/_authenticated/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AuthenticatedKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bootstrap': {
      id: '/_authenticated/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof AuthenticatedBootstrapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attachments': {
      id: '/_authenticated/attachments'
      path: '/attachments'
      fullPath: '/attachments'
      preLoaderRoute: typeof AuthenticatedAttachmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/secrets/': {
      id: '/_authenticated/secrets/'
      path: '/'
      fullPath: '/secrets/'
      preLoaderRoute: typeof AuthenticatedSecretsIndexRouteImport
      parentRoute: typeof AuthenticatedSecretsRoute
    }
    '/_authenticated/routes/': {
      id: '/_authenticated/routes/'
      path: '/'
      fullPath: '/routes/'
      preLoaderRoute: typeof AuthenticatedRoutesIndexRouteImport
      parentRoute: typeof AuthenticatedRoutesRoute
    }
    '/_authenticated/ratelimits/': {
      id: '/_authenticated/ratelimits/'
      path: '/'
      fullPath: '/ratelimits/'
      preLoaderRoute: typeof AuthenticatedRatelimitsIndexRouteImport
      parentRoute: typeof AuthenticatedRatelimitsRoute
    }
    '/_authenticated/providers/': {
      id: '/_authenticated/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof AuthenticatedProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedProvidersRoute
    }
    '/_authenticated/pools/': {
      id: '/_authenticated/pools/'
      path: '/'
      fullPath: '/pools/'
      preLoaderRoute: typeof AuthenticatedPoolsIndexRouteImport
      parentRoute: typeof AuthenticatedPoolsRoute
    }
    '/_authenticated/policies/': {
      id: '/_authenticated/policies/'
      path: '/'
      fullPath: '/policies/'
      preLoaderRoute: typeof AuthenticatedPoliciesIndexRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/models/': {
      id: '/_authenticated/models/'
      path: '/'
      fullPath: '/models/'
      preLoaderRoute: typeof AuthenticatedModelsIndexRouteImport
      parentRoute: typeof AuthenticatedModelsRoute
    }
    '/_authenticated/settings/passthrough': {
      id: '/_authenticated/settings/passthrough'
      path: '/passthrough'
      fullPath: '/settings/passthrough'
      preLoaderRoute: typeof AuthenticatedSettingsPassthroughRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/secrets/new': {
      id: '/_authenticated/secrets/new'
      path: '/new'
      fullPath: '/secrets/new'
      preLoaderRoute: typeof AuthenticatedSecretsNewRouteImport
      parentRoute: typeof AuthenticatedSecretsRoute
    }
    '/_authenticated/secrets/$name': {
      id: '/_authenticated/secrets/$name'
      path: '/$name'
      fullPath: '/secrets/$name'
      preLoaderRoute: typeof AuthenticatedSecretsNameRouteImport
      parentRoute: typeof AuthenticatedSecretsRoute
    }
    '/_authenticated/routes/new': {
      id: '/_authenticated/routes/new'
      path: '/new'
      fullPath: '/routes/new'
      preLoaderRoute: typeof AuthenticatedRoutesNewRouteImport
      parentRoute: typeof AuthenticatedRoutesRoute
    }
    '/_authenticated/routes/$name': {
      id: '/_authenticated/routes/$name'
      path: '/$name'
      fullPath: '/routes/$name'
      preLoaderRoute: typeof AuthenticatedRoutesNameRouteImport
      parentRoute: typeof AuthenticatedRoutesRoute
    }
    '/_authenticated/ratelimits/$name': {
      id: '/_authenticated/ratelimits/$name'
      path: '/$name'
      fullPath: '/ratelimits/$name'
      preLoaderRoute: typeof AuthenticatedRatelimitsNameRouteImport
      parentRoute: typeof AuthenticatedRatelimitsRoute
    }
    '/_authenticated/providers/new': {
      id: '/_authenticated/providers/new'
      path: '/new'
      fullPath: '/providers/new'
      preLoaderRoute: typeof AuthenticatedProvidersNewRouteImport
      parentRoute: typeof AuthenticatedProvidersRoute
    }
    '/_authenticated/providers/$name': {
      id: '/_authenticated/providers/$name'
      path: '/$name'
      fullPath: '/providers/$name'
      preLoaderRoute: typeof AuthenticatedProvidersNameRouteImport
      parentRoute: typeof AuthenticatedProvidersRoute
    }
    '/_authenticated/pools/$name': {
      id: '/_authenticated/pools/$name'
      path: '/$name'
      fullPath: '/pools/$name'
      preLoaderRoute: typeof AuthenticatedPoolsNameRouteImport
      parentRoute: typeof AuthenticatedPoolsRoute
    }
    '/_authenticated/policies/new': {
      id: '/_authenticated/policies/new'
      path: '/new'
      fullPath: '/policies/new'
      preLoaderRoute: typeof AuthenticatedPoliciesNewRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/policies/$name': {
      id: '/_authenticated/policies/$name'
      path: '/$name'
      fullPath: '/policies/$name'
      preLoaderRoute: typeof AuthenticatedPoliciesNameRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/models/new': {
      id: '/_authenticated/models/new'
      path: '/new'
      fullPath: '/models/new'
      preLoaderRoute: typeof AuthenticatedModelsNewRouteImport
      parentRoute: typeof AuthenticatedModelsRoute
    }
    '/_authenticated/models/$name': {
      id: '/_authenticated/models/$name'
      path: '/$name'
      fullPath: '/models/$name'
      preLoaderRoute: typeof AuthenticatedModelsNameRouteImport
      parentRoute: typeof AuthenticatedModelsRoute
    }
    '/_authenticated/keys/$id': {
      id: '/_authenticated/keys/$id'
      path: '/$id'
      fullPath: '/keys/$id'
      preLoaderRoute: typeof AuthenticatedKeysIdRouteImport
      parentRoute: typeof AuthenticatedKeysRoute
    }
    '/_authenticated/secrets/$name/edit': {
      id: '/_authenticated/secrets/$name/edit'
      path: '/edit'
      fullPath: '/secrets/$name/edit'
      preLoaderRoute: typeof AuthenticatedSecretsNameEditRouteImport
      parentRoute: typeof AuthenticatedSecretsNameRoute
    }
    '/_authenticated/routes/$name/edit': {
      id: '/_authenticated/routes/$name/edit'
      path: '/edit'
      fullPath: '/routes/$name/edit'
      preLoaderRoute: typeof AuthenticatedRoutesNameEditRouteImport
      parentRoute: typeof AuthenticatedRoutesNameRoute
    }
    '/_authenticated/providers/$name/edit': {
      id: '/_authenticated/providers/$name/edit'
      path: '/edit'
      fullPath: '/providers/$name/edit'
      preLoaderRoute: typeof AuthenticatedProvidersNameEditRouteImport
      parentRoute: typeof AuthenticatedProvidersNameRoute
    }
    '/_authenticated/policies/rate-limits/new': {
      id: '/_authenticated/policies/rate-limits/new'
      path: '/rate-limits/new'
      fullPath: '/policies/rate-limits/new'
      preLoaderRoute: typeof AuthenticatedPoliciesRateLimitsNewRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/policies/rate-limits/$name': {
      id: '/_authenticated/policies/rate-limits/$name'
      path: '/rate-limits/$name'
      fullPath: '/policies/rate-limits/$name'
      preLoaderRoute: typeof AuthenticatedPoliciesRateLimitsNameRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/models/$name/edit': {
      id: '/_authenticated/models/$name/edit'
      path: '/edit'
      fullPath: '/models/$name/edit'
      preLoaderRoute: typeof AuthenticatedModelsNameEditRouteImport
      parentRoute: typeof AuthenticatedModelsNameRoute
    }
  }
}

interface AuthenticatedKeysRouteChildren {
  AuthenticatedKeysIdRoute: typeof AuthenticatedKeysIdRoute
}

const AuthenticatedKeysRouteChildren: AuthenticatedKeysRouteChildren = {
  AuthenticatedKeysIdRoute: AuthenticatedKeysIdRoute,
}

const AuthenticatedKeysRouteWithChildren =
  AuthenticatedKeysRoute._addFileChildren(AuthenticatedKeysRouteChildren)

interface AuthenticatedModelsNameRouteChildren {
  AuthenticatedModelsNameEditRoute: typeof AuthenticatedModelsNameEditRoute
}

const AuthenticatedModelsNameRouteChildren: AuthenticatedModelsNameRouteChildren =
  {
    AuthenticatedModelsNameEditRoute: AuthenticatedModelsNameEditRoute,
  }

const AuthenticatedModelsNameRouteWithChildren =
  AuthenticatedModelsNameRoute._addFileChildren(
    AuthenticatedModelsNameRouteChildren,
  )

interface AuthenticatedModelsRouteChildren {
  AuthenticatedModelsNameRoute: typeof AuthenticatedModelsNameRouteWithChildren
  AuthenticatedModelsNewRoute: typeof AuthenticatedModelsNewRoute
  AuthenticatedModelsIndexRoute: typeof AuthenticatedModelsIndexRoute
}

const AuthenticatedModelsRouteChildren: AuthenticatedModelsRouteChildren = {
  AuthenticatedModelsNameRoute: AuthenticatedModelsNameRouteWithChildren,
  AuthenticatedModelsNewRoute: AuthenticatedModelsNewRoute,
  AuthenticatedModelsIndexRoute: AuthenticatedModelsIndexRoute,
}

const AuthenticatedModelsRouteWithChildren =
  AuthenticatedModelsRoute._addFileChildren(AuthenticatedModelsRouteChildren)

interface AuthenticatedPoliciesRouteChildren {
  AuthenticatedPoliciesNameRoute: typeof AuthenticatedPoliciesNameRoute
  AuthenticatedPoliciesNewRoute: typeof AuthenticatedPoliciesNewRoute
  AuthenticatedPoliciesIndexRoute: typeof AuthenticatedPoliciesIndexRoute
  AuthenticatedPoliciesRateLimitsNameRoute: typeof AuthenticatedPoliciesRateLimitsNameRoute
  AuthenticatedPoliciesRateLimitsNewRoute: typeof AuthenticatedPoliciesRateLimitsNewRoute
}

const AuthenticatedPoliciesRouteChildren: AuthenticatedPoliciesRouteChildren = {
  AuthenticatedPoliciesNameRoute: AuthenticatedPoliciesNameRoute,
  AuthenticatedPoliciesNewRoute: AuthenticatedPoliciesNewRoute,
  AuthenticatedPoliciesIndexRoute: AuthenticatedPoliciesIndexRoute,
  AuthenticatedPoliciesRateLimitsNameRoute:
    AuthenticatedPoliciesRateLimitsNameRoute,
  AuthenticatedPoliciesRateLimitsNewRoute:
    AuthenticatedPoliciesRateLimitsNewRoute,
}

const AuthenticatedPoliciesRouteWithChildren =
  AuthenticatedPoliciesRoute._addFileChildren(
    AuthenticatedPoliciesRouteChildren,
  )

interface AuthenticatedPoolsRouteChildren {
  AuthenticatedPoolsNameRoute: typeof AuthenticatedPoolsNameRoute
  AuthenticatedPoolsIndexRoute: typeof AuthenticatedPoolsIndexRoute
}

const AuthenticatedPoolsRouteChildren: AuthenticatedPoolsRouteChildren = {
  AuthenticatedPoolsNameRoute: AuthenticatedPoolsNameRoute,
  AuthenticatedPoolsIndexRoute: AuthenticatedPoolsIndexRoute,
}

const AuthenticatedPoolsRouteWithChildren =
  AuthenticatedPoolsRoute._addFileChildren(AuthenticatedPoolsRouteChildren)

interface AuthenticatedProvidersNameRouteChildren {
  AuthenticatedProvidersNameEditRoute: typeof AuthenticatedProvidersNameEditRoute
}

const AuthenticatedProvidersNameRouteChildren: AuthenticatedProvidersNameRouteChildren =
  {
    AuthenticatedProvidersNameEditRoute: AuthenticatedProvidersNameEditRoute,
  }

const AuthenticatedProvidersNameRouteWithChildren =
  AuthenticatedProvidersNameRoute._addFileChildren(
    AuthenticatedProvidersNameRouteChildren,
  )

interface AuthenticatedProvidersRouteChildren {
  AuthenticatedProvidersNameRoute: typeof AuthenticatedProvidersNameRouteWithChildren
  AuthenticatedProvidersNewRoute: typeof AuthenticatedProvidersNewRoute
  AuthenticatedProvidersIndexRoute: typeof AuthenticatedProvidersIndexRoute
}

const AuthenticatedProvidersRouteChildren: AuthenticatedProvidersRouteChildren =
  {
    AuthenticatedProvidersNameRoute:
      AuthenticatedProvidersNameRouteWithChildren,
    AuthenticatedProvidersNewRoute: AuthenticatedProvidersNewRoute,
    AuthenticatedProvidersIndexRoute: AuthenticatedProvidersIndexRoute,
  }

const AuthenticatedProvidersRouteWithChildren =
  AuthenticatedProvidersRoute._addFileChildren(
    AuthenticatedProvidersRouteChildren,
  )

interface AuthenticatedRatelimitsRouteChildren {
  AuthenticatedRatelimitsNameRoute: typeof AuthenticatedRatelimitsNameRoute
  AuthenticatedRatelimitsIndexRoute: typeof AuthenticatedRatelimitsIndexRoute
}

const AuthenticatedRatelimitsRouteChildren: AuthenticatedRatelimitsRouteChildren =
  {
    AuthenticatedRatelimitsNameRoute: AuthenticatedRatelimitsNameRoute,
    AuthenticatedRatelimitsIndexRoute: AuthenticatedRatelimitsIndexRoute,
  }

const AuthenticatedRatelimitsRouteWithChildren =
  AuthenticatedRatelimitsRoute._addFileChildren(
    AuthenticatedRatelimitsRouteChildren,
  )

interface AuthenticatedRoutesNameRouteChildren {
  AuthenticatedRoutesNameEditRoute: typeof AuthenticatedRoutesNameEditRoute
}

const AuthenticatedRoutesNameRouteChildren: AuthenticatedRoutesNameRouteChildren =
  {
    AuthenticatedRoutesNameEditRoute: AuthenticatedRoutesNameEditRoute,
  }

const AuthenticatedRoutesNameRouteWithChildren =
  AuthenticatedRoutesNameRoute._addFileChildren(
    AuthenticatedRoutesNameRouteChildren,
  )

interface AuthenticatedRoutesRouteChildren {
  AuthenticatedRoutesNameRoute: typeof AuthenticatedRoutesNameRouteWithChildren
  AuthenticatedRoutesNewRoute: typeof AuthenticatedRoutesNewRoute
  AuthenticatedRoutesIndexRoute: typeof AuthenticatedRoutesIndexRoute
}

const AuthenticatedRoutesRouteChildren: AuthenticatedRoutesRouteChildren = {
  AuthenticatedRoutesNameRoute: AuthenticatedRoutesNameRouteWithChildren,
  AuthenticatedRoutesNewRoute: AuthenticatedRoutesNewRoute,
  AuthenticatedRoutesIndexRoute: AuthenticatedRoutesIndexRoute,
}

const AuthenticatedRoutesRouteWithChildren =
  AuthenticatedRoutesRoute._addFileChildren(AuthenticatedRoutesRouteChildren)

interface AuthenticatedSecretsNameRouteChildren {
  AuthenticatedSecretsNameEditRoute: typeof AuthenticatedSecretsNameEditRoute
}

const AuthenticatedSecretsNameRouteChildren: AuthenticatedSecretsNameRouteChildren =
  {
    AuthenticatedSecretsNameEditRoute: AuthenticatedSecretsNameEditRoute,
  }

const AuthenticatedSecretsNameRouteWithChildren =
  AuthenticatedSecretsNameRoute._addFileChildren(
    AuthenticatedSecretsNameRouteChildren,
  )

interface AuthenticatedSecretsRouteChildren {
  AuthenticatedSecretsNameRoute: typeof AuthenticatedSecretsNameRouteWithChildren
  AuthenticatedSecretsNewRoute: typeof AuthenticatedSecretsNewRoute
  AuthenticatedSecretsIndexRoute: typeof AuthenticatedSecretsIndexRoute
}

const AuthenticatedSecretsRouteChildren: AuthenticatedSecretsRouteChildren = {
  AuthenticatedSecretsNameRoute: AuthenticatedSecretsNameRouteWithChildren,
  AuthenticatedSecretsNewRoute: AuthenticatedSecretsNewRoute,
  AuthenticatedSecretsIndexRoute: AuthenticatedSecretsIndexRoute,
}

const AuthenticatedSecretsRouteWithChildren =
  AuthenticatedSecretsRoute._addFileChildren(AuthenticatedSecretsRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsPassthroughRoute: typeof AuthenticatedSettingsPassthroughRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsPassthroughRoute: AuthenticatedSettingsPassthroughRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAttachmentsRoute: typeof AuthenticatedAttachmentsRoute
  AuthenticatedBootstrapRoute: typeof AuthenticatedBootstrapRoute
  AuthenticatedKeysRoute: typeof AuthenticatedKeysRouteWithChildren
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRouteWithChildren
  AuthenticatedPoliciesRoute: typeof AuthenticatedPoliciesRouteWithChildren
  AuthenticatedPoolsRoute: typeof AuthenticatedPoolsRouteWithChildren
  AuthenticatedProvidersRoute: typeof AuthenticatedProvidersRouteWithChildren
  AuthenticatedRatelimitsRoute: typeof AuthenticatedRatelimitsRouteWithChildren
  AuthenticatedRoutersRoute: typeof AuthenticatedRoutersRoute
  AuthenticatedRoutesRoute: typeof AuthenticatedRoutesRouteWithChildren
  AuthenticatedSecretsRoute: typeof AuthenticatedSecretsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAttachmentsRoute: AuthenticatedAttachmentsRoute,
  AuthenticatedBootstrapRoute: AuthenticatedBootstrapRoute,
  AuthenticatedKeysRoute: AuthenticatedKeysRouteWithChildren,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedModelsRoute: AuthenticatedModelsRouteWithChildren,
  AuthenticatedPoliciesRoute: AuthenticatedPoliciesRouteWithChildren,
  AuthenticatedPoolsRoute: AuthenticatedPoolsRouteWithChildren,
  AuthenticatedProvidersRoute: AuthenticatedProvidersRouteWithChildren,
  AuthenticatedRatelimitsRoute: AuthenticatedRatelimitsRouteWithChildren,
  AuthenticatedRoutersRoute: AuthenticatedRoutersRoute,
  AuthenticatedRoutesRoute: AuthenticatedRoutesRouteWithChildren,
  AuthenticatedSecretsRoute: AuthenticatedSecretsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
