/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsageRouteImport } from './routes/_authenticated/usage'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServiceAccountsRouteImport } from './routes/_authenticated/service-accounts'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedPoliciesRouteImport } from './routes/_authenticated/policies'
import { Route as AuthenticatedModelsRouteImport } from './routes/_authenticated/models'
import { Route as AuthenticatedKeysRouteImport } from './routes/_authenticated/keys'
import { Route as AuthenticatedHostKeysRouteImport } from './routes/_authenticated/host-keys'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedBootstrapRouteImport } from './routes/_authenticated/bootstrap'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedServiceAccountsIndexRouteImport } from './routes/_authenticated/service-accounts.index'
import { Route as AuthenticatedPricingIndexRouteImport } from './routes/_authenticated/pricing.index'
import { Route as AuthenticatedPoliciesIndexRouteImport } from './routes/_authenticated/policies.index'
import { Route as AuthenticatedModelsIndexRouteImport } from './routes/_authenticated/models.index'
import { Route as AuthenticatedLogsIndexRouteImport } from './routes/_authenticated/logs.index'
import { Route as AuthenticatedHostKeysIndexRouteImport } from './routes/_authenticated/host-keys.index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups.index'
import { Route as AuthenticatedSettingsRateLimitsRouteImport } from './routes/_authenticated/settings.rate-limits'
import { Route as AuthenticatedSettingsProxyModeRouteImport } from './routes/_authenticated/settings.proxy-mode'
import { Route as AuthenticatedSettingsPermissionsRouteImport } from './routes/_authenticated/settings.permissions'
import { Route as AuthenticatedSettingsPayloadLoggingRouteImport } from './routes/_authenticated/settings.payload-logging'
import { Route as AuthenticatedServiceAccountsNewRouteImport } from './routes/_authenticated/service-accounts.new'
import { Route as AuthenticatedServiceAccountsNameRouteImport } from './routes/_authenticated/service-accounts.$name'
import { Route as AuthenticatedProvidersNameRouteImport } from './routes/_authenticated/providers.$name'
import { Route as AuthenticatedPricingNewRouteImport } from './routes/_authenticated/pricing.new'
import { Route as AuthenticatedPricingNameRouteImport } from './routes/_authenticated/pricing.$name'
import { Route as AuthenticatedPoliciesNewRouteImport } from './routes/_authenticated/policies.new'
import { Route as AuthenticatedPoliciesNameRouteImport } from './routes/_authenticated/policies.$name'
import { Route as AuthenticatedModelsNewRouteImport } from './routes/_authenticated/models.new'
import { Route as AuthenticatedModelsNameRouteImport } from './routes/_authenticated/models.$name'
import { Route as AuthenticatedLogsRequestIdRouteImport } from './routes/_authenticated/logs.$requestId'
import { Route as AuthenticatedKeysNewRouteImport } from './routes/_authenticated/keys_.new'
import { Route as AuthenticatedKeysNameRouteImport } from './routes/_authenticated/keys_.$name'
import { Route as AuthenticatedHostsNameRouteImport } from './routes/_authenticated/hosts.$name'
import { Route as AuthenticatedHostKeysNewRouteImport } from './routes/_authenticated/host-keys.new'
import { Route as AuthenticatedHostKeysNameRouteImport } from './routes/_authenticated/host-keys.$name'
import { Route as AuthenticatedGroupsNewRouteImport } from './routes/_authenticated/groups.new'
import { Route as AuthenticatedGroupsNameRouteImport } from './routes/_authenticated/groups.$name'
import { Route as AuthenticatedServiceAccountsNameEditRouteImport } from './routes/_authenticated/service-accounts.$name_.edit'
import { Route as AuthenticatedPricingNameEditRouteImport } from './routes/_authenticated/pricing.$name_.edit'
import { Route as AuthenticatedPoliciesRateLimitsNewRouteImport } from './routes/_authenticated/policies.rate-limits.new'
import { Route as AuthenticatedPoliciesRateLimitsNameRouteImport } from './routes/_authenticated/policies.rate-limits.$name'
import { Route as AuthenticatedPoliciesNameEditRouteImport } from './routes/_authenticated/policies.$name_.edit'
import { Route as AuthenticatedModelsNameEditRouteImport } from './routes/_authenticated/models.$name.edit'
import { Route as AuthenticatedKeysNameEditRouteImport } from './routes/_authenticated/keys_.$name_.edit'
import { Route as AuthenticatedHostKeysNameEditRouteImport } from './routes/_authenticated/host-keys.$name_.edit'
import { Route as AuthenticatedGroupsNameEditRouteImport } from './routes/_authenticated/groups.$name_.edit'
import { Route as AuthenticatedPoliciesRateLimitsNameEditRouteImport } from './routes/_authenticated/policies.rate-limits.$name_.edit'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServiceAccountsRoute =
  AuthenticatedServiceAccountsRouteImport.update({
    id: '/service-accounts',
    path: '/service-accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoliciesRoute = AuthenticatedPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKeysRoute = AuthenticatedKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHostKeysRoute = AuthenticatedHostKeysRouteImport.update({
  id: '/host-keys',
  path: '/host-keys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBootstrapRoute = AuthenticatedBootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedServiceAccountsIndexRoute =
  AuthenticatedServiceAccountsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedServiceAccountsRoute,
  } as any)
const AuthenticatedPricingIndexRoute =
  AuthenticatedPricingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPricingRoute,
  } as any)
const AuthenticatedPoliciesIndexRoute =
  AuthenticatedPoliciesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedModelsIndexRoute =
  AuthenticatedModelsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedModelsRoute,
  } as any)
const AuthenticatedLogsIndexRoute = AuthenticatedLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHostKeysIndexRoute =
  AuthenticatedHostKeysIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHostKeysRoute,
  } as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGroupsRoute,
  } as any)
const AuthenticatedSettingsRateLimitsRoute =
  AuthenticatedSettingsRateLimitsRouteImport.update({
    id: '/rate-limits',
    path: '/rate-limits',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProxyModeRoute =
  AuthenticatedSettingsProxyModeRouteImport.update({
    id: '/proxy-mode',
    path: '/proxy-mode',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPermissionsRoute =
  AuthenticatedSettingsPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPayloadLoggingRoute =
  AuthenticatedSettingsPayloadLoggingRouteImport.update({
    id: '/payload-logging',
    path: '/payload-logging',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedServiceAccountsNewRoute =
  AuthenticatedServiceAccountsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedServiceAccountsRoute,
  } as any)
const AuthenticatedServiceAccountsNameRoute =
  AuthenticatedServiceAccountsNameRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => AuthenticatedServiceAccountsRoute,
  } as any)
const AuthenticatedProvidersNameRoute =
  AuthenticatedProvidersNameRouteImport.update({
    id: '/providers/$name',
    path: '/providers/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPricingNewRoute = AuthenticatedPricingNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedPricingRoute,
} as any)
const AuthenticatedPricingNameRoute =
  AuthenticatedPricingNameRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => AuthenticatedPricingRoute,
  } as any)
const AuthenticatedPoliciesNewRoute =
  AuthenticatedPoliciesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedPoliciesNameRoute =
  AuthenticatedPoliciesNameRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedModelsNewRoute = AuthenticatedModelsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedModelsRoute,
} as any)
const AuthenticatedModelsNameRoute = AuthenticatedModelsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AuthenticatedModelsRoute,
} as any)
const AuthenticatedLogsRequestIdRoute =
  AuthenticatedLogsRequestIdRouteImport.update({
    id: '/logs/$requestId',
    path: '/logs/$requestId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKeysNewRoute = AuthenticatedKeysNewRouteImport.update({
  id: '/keys_/new',
  path: '/keys/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKeysNameRoute = AuthenticatedKeysNameRouteImport.update({
  id: '/keys_/$name',
  path: '/keys/$name',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHostsNameRoute = AuthenticatedHostsNameRouteImport.update({
  id: '/hosts/$name',
  path: '/hosts/$name',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHostKeysNewRoute =
  AuthenticatedHostKeysNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedHostKeysRoute,
  } as any)
const AuthenticatedHostKeysNameRoute =
  AuthenticatedHostKeysNameRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => AuthenticatedHostKeysRoute,
  } as any)
const AuthenticatedGroupsNewRoute = AuthenticatedGroupsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedGroupsRoute,
} as any)
const AuthenticatedGroupsNameRoute = AuthenticatedGroupsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AuthenticatedGroupsRoute,
} as any)
const AuthenticatedServiceAccountsNameEditRoute =
  AuthenticatedServiceAccountsNameEditRouteImport.update({
    id: '/$name_/edit',
    path: '/$name/edit',
    getParentRoute: () => AuthenticatedServiceAccountsRoute,
  } as any)
const AuthenticatedPricingNameEditRoute =
  AuthenticatedPricingNameEditRouteImport.update({
    id: '/$name_/edit',
    path: '/$name/edit',
    getParentRoute: () => AuthenticatedPricingRoute,
  } as any)
const AuthenticatedPoliciesRateLimitsNewRoute =
  AuthenticatedPoliciesRateLimitsNewRouteImport.update({
    id: '/rate-limits/new',
    path: '/rate-limits/new',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedPoliciesRateLimitsNameRoute =
  AuthenticatedPoliciesRateLimitsNameRouteImport.update({
    id: '/rate-limits/$name',
    path: '/rate-limits/$name',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedPoliciesNameEditRoute =
  AuthenticatedPoliciesNameEditRouteImport.update({
    id: '/$name_/edit',
    path: '/$name/edit',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedModelsNameEditRoute =
  AuthenticatedModelsNameEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedModelsNameRoute,
  } as any)
const AuthenticatedKeysNameEditRoute =
  AuthenticatedKeysNameEditRouteImport.update({
    id: '/keys_/$name_/edit',
    path: '/keys/$name/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHostKeysNameEditRoute =
  AuthenticatedHostKeysNameEditRouteImport.update({
    id: '/$name_/edit',
    path: '/$name/edit',
    getParentRoute: () => AuthenticatedHostKeysRoute,
  } as any)
const AuthenticatedGroupsNameEditRoute =
  AuthenticatedGroupsNameEditRouteImport.update({
    id: '/$name_/edit',
    path: '/$name/edit',
    getParentRoute: () => AuthenticatedGroupsRoute,
  } as any)
const AuthenticatedPoliciesRateLimitsNameEditRoute =
  AuthenticatedPoliciesRateLimitsNameEditRouteImport.update({
    id: '/rate-limits/$name_/edit',
    path: '/rate-limits/$name/edit',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/bootstrap': typeof AuthenticatedBootstrapRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/host-keys': typeof AuthenticatedHostKeysRouteWithChildren
  '/keys': typeof AuthenticatedKeysRoute
  '/models': typeof AuthenticatedModelsRouteWithChildren
  '/policies': typeof AuthenticatedPoliciesRouteWithChildren
  '/pricing': typeof AuthenticatedPricingRouteWithChildren
  '/service-accounts': typeof AuthenticatedServiceAccountsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/usage': typeof AuthenticatedUsageRoute
  '/groups/$name': typeof AuthenticatedGroupsNameRoute
  '/groups/new': typeof AuthenticatedGroupsNewRoute
  '/host-keys/$name': typeof AuthenticatedHostKeysNameRoute
  '/host-keys/new': typeof AuthenticatedHostKeysNewRoute
  '/hosts/$name': typeof AuthenticatedHostsNameRoute
  '/keys/$name': typeof AuthenticatedKeysNameRoute
  '/keys/new': typeof AuthenticatedKeysNewRoute
  '/logs/$requestId': typeof AuthenticatedLogsRequestIdRoute
  '/models/$name': typeof AuthenticatedModelsNameRouteWithChildren
  '/models/new': typeof AuthenticatedModelsNewRoute
  '/policies/$name': typeof AuthenticatedPoliciesNameRoute
  '/policies/new': typeof AuthenticatedPoliciesNewRoute
  '/pricing/$name': typeof AuthenticatedPricingNameRoute
  '/pricing/new': typeof AuthenticatedPricingNewRoute
  '/providers/$name': typeof AuthenticatedProvidersNameRoute
  '/service-accounts/$name': typeof AuthenticatedServiceAccountsNameRoute
  '/service-accounts/new': typeof AuthenticatedServiceAccountsNewRoute
  '/settings/payload-logging': typeof AuthenticatedSettingsPayloadLoggingRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/settings/proxy-mode': typeof AuthenticatedSettingsProxyModeRoute
  '/settings/rate-limits': typeof AuthenticatedSettingsRateLimitsRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/host-keys/': typeof AuthenticatedHostKeysIndexRoute
  '/logs/': typeof AuthenticatedLogsIndexRoute
  '/models/': typeof AuthenticatedModelsIndexRoute
  '/policies/': typeof AuthenticatedPoliciesIndexRoute
  '/pricing/': typeof AuthenticatedPricingIndexRoute
  '/service-accounts/': typeof AuthenticatedServiceAccountsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/groups/$name/edit': typeof AuthenticatedGroupsNameEditRoute
  '/host-keys/$name/edit': typeof AuthenticatedHostKeysNameEditRoute
  '/keys/$name/edit': typeof AuthenticatedKeysNameEditRoute
  '/models/$name/edit': typeof AuthenticatedModelsNameEditRoute
  '/policies/$name/edit': typeof AuthenticatedPoliciesNameEditRoute
  '/policies/rate-limits/$name': typeof AuthenticatedPoliciesRateLimitsNameRoute
  '/policies/rate-limits/new': typeof AuthenticatedPoliciesRateLimitsNewRoute
  '/pricing/$name/edit': typeof AuthenticatedPricingNameEditRoute
  '/service-accounts/$name/edit': typeof AuthenticatedServiceAccountsNameEditRoute
  '/policies/rate-limits/$name/edit': typeof AuthenticatedPoliciesRateLimitsNameEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/bootstrap': typeof AuthenticatedBootstrapRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/': typeof AuthenticatedIndexRoute
  '/groups/$name': typeof AuthenticatedGroupsNameRoute
  '/groups/new': typeof AuthenticatedGroupsNewRoute
  '/host-keys/$name': typeof AuthenticatedHostKeysNameRoute
  '/host-keys/new': typeof AuthenticatedHostKeysNewRoute
  '/hosts/$name': typeof AuthenticatedHostsNameRoute
  '/keys/$name': typeof AuthenticatedKeysNameRoute
  '/keys/new': typeof AuthenticatedKeysNewRoute
  '/logs/$requestId': typeof AuthenticatedLogsRequestIdRoute
  '/models/$name': typeof AuthenticatedModelsNameRouteWithChildren
  '/models/new': typeof AuthenticatedModelsNewRoute
  '/policies/$name': typeof AuthenticatedPoliciesNameRoute
  '/policies/new': typeof AuthenticatedPoliciesNewRoute
  '/pricing/$name': typeof AuthenticatedPricingNameRoute
  '/pricing/new': typeof AuthenticatedPricingNewRoute
  '/providers/$name': typeof AuthenticatedProvidersNameRoute
  '/service-accounts/$name': typeof AuthenticatedServiceAccountsNameRoute
  '/service-accounts/new': typeof AuthenticatedServiceAccountsNewRoute
  '/settings/payload-logging': typeof AuthenticatedSettingsPayloadLoggingRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/settings/proxy-mode': typeof AuthenticatedSettingsProxyModeRoute
  '/settings/rate-limits': typeof AuthenticatedSettingsRateLimitsRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/host-keys': typeof AuthenticatedHostKeysIndexRoute
  '/logs': typeof AuthenticatedLogsIndexRoute
  '/models': typeof AuthenticatedModelsIndexRoute
  '/policies': typeof AuthenticatedPoliciesIndexRoute
  '/pricing': typeof AuthenticatedPricingIndexRoute
  '/service-accounts': typeof AuthenticatedServiceAccountsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/groups/$name/edit': typeof AuthenticatedGroupsNameEditRoute
  '/host-keys/$name/edit': typeof AuthenticatedHostKeysNameEditRoute
  '/keys/$name/edit': typeof AuthenticatedKeysNameEditRoute
  '/models/$name/edit': typeof AuthenticatedModelsNameEditRoute
  '/policies/$name/edit': typeof AuthenticatedPoliciesNameEditRoute
  '/policies/rate-limits/$name': typeof AuthenticatedPoliciesRateLimitsNameRoute
  '/policies/rate-limits/new': typeof AuthenticatedPoliciesRateLimitsNewRoute
  '/pricing/$name/edit': typeof AuthenticatedPricingNameEditRoute
  '/service-accounts/$name/edit': typeof AuthenticatedServiceAccountsNameEditRoute
  '/policies/rate-limits/$name/edit': typeof AuthenticatedPoliciesRateLimitsNameEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_authenticated/bootstrap': typeof AuthenticatedBootstrapRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/_authenticated/host-keys': typeof AuthenticatedHostKeysRouteWithChildren
  '/_authenticated/keys': typeof AuthenticatedKeysRoute
  '/_authenticated/models': typeof AuthenticatedModelsRouteWithChildren
  '/_authenticated/policies': typeof AuthenticatedPoliciesRouteWithChildren
  '/_authenticated/pricing': typeof AuthenticatedPricingRouteWithChildren
  '/_authenticated/service-accounts': typeof AuthenticatedServiceAccountsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/usage': typeof AuthenticatedUsageRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/groups/$name': typeof AuthenticatedGroupsNameRoute
  '/_authenticated/groups/new': typeof AuthenticatedGroupsNewRoute
  '/_authenticated/host-keys/$name': typeof AuthenticatedHostKeysNameRoute
  '/_authenticated/host-keys/new': typeof AuthenticatedHostKeysNewRoute
  '/_authenticated/hosts/$name': typeof AuthenticatedHostsNameRoute
  '/_authenticated/keys_/$name': typeof AuthenticatedKeysNameRoute
  '/_authenticated/keys_/new': typeof AuthenticatedKeysNewRoute
  '/_authenticated/logs/$requestId': typeof AuthenticatedLogsRequestIdRoute
  '/_authenticated/models/$name': typeof AuthenticatedModelsNameRouteWithChildren
  '/_authenticated/models/new': typeof AuthenticatedModelsNewRoute
  '/_authenticated/policies/$name': typeof AuthenticatedPoliciesNameRoute
  '/_authenticated/policies/new': typeof AuthenticatedPoliciesNewRoute
  '/_authenticated/pricing/$name': typeof AuthenticatedPricingNameRoute
  '/_authenticated/pricing/new': typeof AuthenticatedPricingNewRoute
  '/_authenticated/providers/$name': typeof AuthenticatedProvidersNameRoute
  '/_authenticated/service-accounts/$name': typeof AuthenticatedServiceAccountsNameRoute
  '/_authenticated/service-accounts/new': typeof AuthenticatedServiceAccountsNewRoute
  '/_authenticated/settings/payload-logging': typeof AuthenticatedSettingsPayloadLoggingRoute
  '/_authenticated/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/_authenticated/settings/proxy-mode': typeof AuthenticatedSettingsProxyModeRoute
  '/_authenticated/settings/rate-limits': typeof AuthenticatedSettingsRateLimitsRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/host-keys/': typeof AuthenticatedHostKeysIndexRoute
  '/_authenticated/logs/': typeof AuthenticatedLogsIndexRoute
  '/_authenticated/models/': typeof AuthenticatedModelsIndexRoute
  '/_authenticated/policies/': typeof AuthenticatedPoliciesIndexRoute
  '/_authenticated/pricing/': typeof AuthenticatedPricingIndexRoute
  '/_authenticated/service-accounts/': typeof AuthenticatedServiceAccountsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/groups/$name_/edit': typeof AuthenticatedGroupsNameEditRoute
  '/_authenticated/host-keys/$name_/edit': typeof AuthenticatedHostKeysNameEditRoute
  '/_authenticated/keys_/$name_/edit': typeof AuthenticatedKeysNameEditRoute
  '/_authenticated/models/$name/edit': typeof AuthenticatedModelsNameEditRoute
  '/_authenticated/policies/$name_/edit': typeof AuthenticatedPoliciesNameEditRoute
  '/_authenticated/policies/rate-limits/$name': typeof AuthenticatedPoliciesRateLimitsNameRoute
  '/_authenticated/policies/rate-limits/new': typeof AuthenticatedPoliciesRateLimitsNewRoute
  '/_authenticated/pricing/$name_/edit': typeof AuthenticatedPricingNameEditRoute
  '/_authenticated/service-accounts/$name_/edit': typeof AuthenticatedServiceAccountsNameEditRoute
  '/_authenticated/policies/rate-limits/$name_/edit': typeof AuthenticatedPoliciesRateLimitsNameEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/bootstrap'
    | '/groups'
    | '/host-keys'
    | '/keys'
    | '/models'
    | '/policies'
    | '/pricing'
    | '/service-accounts'
    | '/settings'
    | '/usage'
    | '/groups/$name'
    | '/groups/new'
    | '/host-keys/$name'
    | '/host-keys/new'
    | '/hosts/$name'
    | '/keys/$name'
    | '/keys/new'
    | '/logs/$requestId'
    | '/models/$name'
    | '/models/new'
    | '/policies/$name'
    | '/policies/new'
    | '/pricing/$name'
    | '/pricing/new'
    | '/providers/$name'
    | '/service-accounts/$name'
    | '/service-accounts/new'
    | '/settings/payload-logging'
    | '/settings/permissions'
    | '/settings/proxy-mode'
    | '/settings/rate-limits'
    | '/groups/'
    | '/host-keys/'
    | '/logs/'
    | '/models/'
    | '/policies/'
    | '/pricing/'
    | '/service-accounts/'
    | '/settings/'
    | '/groups/$name/edit'
    | '/host-keys/$name/edit'
    | '/keys/$name/edit'
    | '/models/$name/edit'
    | '/policies/$name/edit'
    | '/policies/rate-limits/$name'
    | '/policies/rate-limits/new'
    | '/pricing/$name/edit'
    | '/service-accounts/$name/edit'
    | '/policies/rate-limits/$name/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/bootstrap'
    | '/keys'
    | '/usage'
    | '/'
    | '/groups/$name'
    | '/groups/new'
    | '/host-keys/$name'
    | '/host-keys/new'
    | '/hosts/$name'
    | '/keys/$name'
    | '/keys/new'
    | '/logs/$requestId'
    | '/models/$name'
    | '/models/new'
    | '/policies/$name'
    | '/policies/new'
    | '/pricing/$name'
    | '/pricing/new'
    | '/providers/$name'
    | '/service-accounts/$name'
    | '/service-accounts/new'
    | '/settings/payload-logging'
    | '/settings/permissions'
    | '/settings/proxy-mode'
    | '/settings/rate-limits'
    | '/groups'
    | '/host-keys'
    | '/logs'
    | '/models'
    | '/policies'
    | '/pricing'
    | '/service-accounts'
    | '/settings'
    | '/groups/$name/edit'
    | '/host-keys/$name/edit'
    | '/keys/$name/edit'
    | '/models/$name/edit'
    | '/policies/$name/edit'
    | '/policies/rate-limits/$name'
    | '/policies/rate-limits/new'
    | '/pricing/$name/edit'
    | '/service-accounts/$name/edit'
    | '/policies/rate-limits/$name/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/setup'
    | '/_authenticated/bootstrap'
    | '/_authenticated/groups'
    | '/_authenticated/host-keys'
    | '/_authenticated/keys'
    | '/_authenticated/models'
    | '/_authenticated/policies'
    | '/_authenticated/pricing'
    | '/_authenticated/service-accounts'
    | '/_authenticated/settings'
    | '/_authenticated/usage'
    | '/_authenticated/'
    | '/_authenticated/groups/$name'
    | '/_authenticated/groups/new'
    | '/_authenticated/host-keys/$name'
    | '/_authenticated/host-keys/new'
    | '/_authenticated/hosts/$name'
    | '/_authenticated/keys_/$name'
    | '/_authenticated/keys_/new'
    | '/_authenticated/logs/$requestId'
    | '/_authenticated/models/$name'
    | '/_authenticated/models/new'
    | '/_authenticated/policies/$name'
    | '/_authenticated/policies/new'
    | '/_authenticated/pricing/$name'
    | '/_authenticated/pricing/new'
    | '/_authenticated/providers/$name'
    | '/_authenticated/service-accounts/$name'
    | '/_authenticated/service-accounts/new'
    | '/_authenticated/settings/payload-logging'
    | '/_authenticated/settings/permissions'
    | '/_authenticated/settings/proxy-mode'
    | '/_authenticated/settings/rate-limits'
    | '/_authenticated/groups/'
    | '/_authenticated/host-keys/'
    | '/_authenticated/logs/'
    | '/_authenticated/models/'
    | '/_authenticated/policies/'
    | '/_authenticated/pricing/'
    | '/_authenticated/service-accounts/'
    | '/_authenticated/settings/'
    | '/_authenticated/groups/$name_/edit'
    | '/_authenticated/host-keys/$name_/edit'
    | '/_authenticated/keys_/$name_/edit'
    | '/_authenticated/models/$name/edit'
    | '/_authenticated/policies/$name_/edit'
    | '/_authenticated/policies/rate-limits/$name'
    | '/_authenticated/policies/rate-limits/new'
    | '/_authenticated/pricing/$name_/edit'
    | '/_authenticated/service-accounts/$name_/edit'
    | '/_authenticated/policies/rate-limits/$name_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usage': {
      id: '/_authenticated/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/service-accounts': {
      id: '/_authenticated/service-accounts'
      path: '/service-accounts'
      fullPath: '/service-accounts'
      preLoaderRoute: typeof AuthenticatedServiceAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/policies': {
      id: '/_authenticated/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthenticatedPoliciesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/models': {
      id: '/_authenticated/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/keys': {
      id: '/_authenticated/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AuthenticatedKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/host-keys': {
      id: '/_authenticated/host-keys'
      path: '/host-keys'
      fullPath: '/host-keys'
      preLoaderRoute: typeof AuthenticatedHostKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bootstrap': {
      id: '/_authenticated/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof AuthenticatedBootstrapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/service-accounts/': {
      id: '/_authenticated/service-accounts/'
      path: '/'
      fullPath: '/service-accounts/'
      preLoaderRoute: typeof AuthenticatedServiceAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedServiceAccountsRoute
    }
    '/_authenticated/pricing/': {
      id: '/_authenticated/pricing/'
      path: '/'
      fullPath: '/pricing/'
      preLoaderRoute: typeof AuthenticatedPricingIndexRouteImport
      parentRoute: typeof AuthenticatedPricingRoute
    }
    '/_authenticated/policies/': {
      id: '/_authenticated/policies/'
      path: '/'
      fullPath: '/policies/'
      preLoaderRoute: typeof AuthenticatedPoliciesIndexRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/models/': {
      id: '/_authenticated/models/'
      path: '/'
      fullPath: '/models/'
      preLoaderRoute: typeof AuthenticatedModelsIndexRouteImport
      parentRoute: typeof AuthenticatedModelsRoute
    }
    '/_authenticated/logs/': {
      id: '/_authenticated/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof AuthenticatedLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/host-keys/': {
      id: '/_authenticated/host-keys/'
      path: '/'
      fullPath: '/host-keys/'
      preLoaderRoute: typeof AuthenticatedHostKeysIndexRouteImport
      parentRoute: typeof AuthenticatedHostKeysRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
    '/_authenticated/settings/rate-limits': {
      id: '/_authenticated/settings/rate-limits'
      path: '/rate-limits'
      fullPath: '/settings/rate-limits'
      preLoaderRoute: typeof AuthenticatedSettingsRateLimitsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/proxy-mode': {
      id: '/_authenticated/settings/proxy-mode'
      path: '/proxy-mode'
      fullPath: '/settings/proxy-mode'
      preLoaderRoute: typeof AuthenticatedSettingsProxyModeRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/permissions': {
      id: '/_authenticated/settings/permissions'
      path: '/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof AuthenticatedSettingsPermissionsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/payload-logging': {
      id: '/_authenticated/settings/payload-logging'
      path: '/payload-logging'
      fullPath: '/settings/payload-logging'
      preLoaderRoute: typeof AuthenticatedSettingsPayloadLoggingRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/service-accounts/new': {
      id: '/_authenticated/service-accounts/new'
      path: '/new'
      fullPath: '/service-accounts/new'
      preLoaderRoute: typeof AuthenticatedServiceAccountsNewRouteImport
      parentRoute: typeof AuthenticatedServiceAccountsRoute
    }
    '/_authenticated/service-accounts/$name': {
      id: '/_authenticated/service-accounts/$name'
      path: '/$name'
      fullPath: '/service-accounts/$name'
      preLoaderRoute: typeof AuthenticatedServiceAccountsNameRouteImport
      parentRoute: typeof AuthenticatedServiceAccountsRoute
    }
    '/_authenticated/providers/$name': {
      id: '/_authenticated/providers/$name'
      path: '/providers/$name'
      fullPath: '/providers/$name'
      preLoaderRoute: typeof AuthenticatedProvidersNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing/new': {
      id: '/_authenticated/pricing/new'
      path: '/new'
      fullPath: '/pricing/new'
      preLoaderRoute: typeof AuthenticatedPricingNewRouteImport
      parentRoute: typeof AuthenticatedPricingRoute
    }
    '/_authenticated/pricing/$name': {
      id: '/_authenticated/pricing/$name'
      path: '/$name'
      fullPath: '/pricing/$name'
      preLoaderRoute: typeof AuthenticatedPricingNameRouteImport
      parentRoute: typeof AuthenticatedPricingRoute
    }
    '/_authenticated/policies/new': {
      id: '/_authenticated/policies/new'
      path: '/new'
      fullPath: '/policies/new'
      preLoaderRoute: typeof AuthenticatedPoliciesNewRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/policies/$name': {
      id: '/_authenticated/policies/$name'
      path: '/$name'
      fullPath: '/policies/$name'
      preLoaderRoute: typeof AuthenticatedPoliciesNameRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/models/new': {
      id: '/_authenticated/models/new'
      path: '/new'
      fullPath: '/models/new'
      preLoaderRoute: typeof AuthenticatedModelsNewRouteImport
      parentRoute: typeof AuthenticatedModelsRoute
    }
    '/_authenticated/models/$name': {
      id: '/_authenticated/models/$name'
      path: '/$name'
      fullPath: '/models/$name'
      preLoaderRoute: typeof AuthenticatedModelsNameRouteImport
      parentRoute: typeof AuthenticatedModelsRoute
    }
    '/_authenticated/logs/$requestId': {
      id: '/_authenticated/logs/$requestId'
      path: '/logs/$requestId'
      fullPath: '/logs/$requestId'
      preLoaderRoute: typeof AuthenticatedLogsRequestIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/keys_/new': {
      id: '/_authenticated/keys_/new'
      path: '/keys/new'
      fullPath: '/keys/new'
      preLoaderRoute: typeof AuthenticatedKeysNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/keys_/$name': {
      id: '/_authenticated/keys_/$name'
      path: '/keys/$name'
      fullPath: '/keys/$name'
      preLoaderRoute: typeof AuthenticatedKeysNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosts/$name': {
      id: '/_authenticated/hosts/$name'
      path: '/hosts/$name'
      fullPath: '/hosts/$name'
      preLoaderRoute: typeof AuthenticatedHostsNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/host-keys/new': {
      id: '/_authenticated/host-keys/new'
      path: '/new'
      fullPath: '/host-keys/new'
      preLoaderRoute: typeof AuthenticatedHostKeysNewRouteImport
      parentRoute: typeof AuthenticatedHostKeysRoute
    }
    '/_authenticated/host-keys/$name': {
      id: '/_authenticated/host-keys/$name'
      path: '/$name'
      fullPath: '/host-keys/$name'
      preLoaderRoute: typeof AuthenticatedHostKeysNameRouteImport
      parentRoute: typeof AuthenticatedHostKeysRoute
    }
    '/_authenticated/groups/new': {
      id: '/_authenticated/groups/new'
      path: '/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof AuthenticatedGroupsNewRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
    '/_authenticated/groups/$name': {
      id: '/_authenticated/groups/$name'
      path: '/$name'
      fullPath: '/groups/$name'
      preLoaderRoute: typeof AuthenticatedGroupsNameRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
    '/_authenticated/service-accounts/$name_/edit': {
      id: '/_authenticated/service-accounts/$name_/edit'
      path: '/$name/edit'
      fullPath: '/service-accounts/$name/edit'
      preLoaderRoute: typeof AuthenticatedServiceAccountsNameEditRouteImport
      parentRoute: typeof AuthenticatedServiceAccountsRoute
    }
    '/_authenticated/pricing/$name_/edit': {
      id: '/_authenticated/pricing/$name_/edit'
      path: '/$name/edit'
      fullPath: '/pricing/$name/edit'
      preLoaderRoute: typeof AuthenticatedPricingNameEditRouteImport
      parentRoute: typeof AuthenticatedPricingRoute
    }
    '/_authenticated/policies/rate-limits/new': {
      id: '/_authenticated/policies/rate-limits/new'
      path: '/rate-limits/new'
      fullPath: '/policies/rate-limits/new'
      preLoaderRoute: typeof AuthenticatedPoliciesRateLimitsNewRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/policies/rate-limits/$name': {
      id: '/_authenticated/policies/rate-limits/$name'
      path: '/rate-limits/$name'
      fullPath: '/policies/rate-limits/$name'
      preLoaderRoute: typeof AuthenticatedPoliciesRateLimitsNameRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/policies/$name_/edit': {
      id: '/_authenticated/policies/$name_/edit'
      path: '/$name/edit'
      fullPath: '/policies/$name/edit'
      preLoaderRoute: typeof AuthenticatedPoliciesNameEditRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/models/$name/edit': {
      id: '/_authenticated/models/$name/edit'
      path: '/edit'
      fullPath: '/models/$name/edit'
      preLoaderRoute: typeof AuthenticatedModelsNameEditRouteImport
      parentRoute: typeof AuthenticatedModelsNameRoute
    }
    '/_authenticated/keys_/$name_/edit': {
      id: '/_authenticated/keys_/$name_/edit'
      path: '/keys/$name/edit'
      fullPath: '/keys/$name/edit'
      preLoaderRoute: typeof AuthenticatedKeysNameEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/host-keys/$name_/edit': {
      id: '/_authenticated/host-keys/$name_/edit'
      path: '/$name/edit'
      fullPath: '/host-keys/$name/edit'
      preLoaderRoute: typeof AuthenticatedHostKeysNameEditRouteImport
      parentRoute: typeof AuthenticatedHostKeysRoute
    }
    '/_authenticated/groups/$name_/edit': {
      id: '/_authenticated/groups/$name_/edit'
      path: '/$name/edit'
      fullPath: '/groups/$name/edit'
      preLoaderRoute: typeof AuthenticatedGroupsNameEditRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
    '/_authenticated/policies/rate-limits/$name_/edit': {
      id: '/_authenticated/policies/rate-limits/$name_/edit'
      path: '/rate-limits/$name/edit'
      fullPath: '/policies/rate-limits/$name/edit'
      preLoaderRoute: typeof AuthenticatedPoliciesRateLimitsNameEditRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
  }
}

interface AuthenticatedGroupsRouteChildren {
  AuthenticatedGroupsNameRoute: typeof AuthenticatedGroupsNameRoute
  AuthenticatedGroupsNewRoute: typeof AuthenticatedGroupsNewRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedGroupsNameEditRoute: typeof AuthenticatedGroupsNameEditRoute
}

const AuthenticatedGroupsRouteChildren: AuthenticatedGroupsRouteChildren = {
  AuthenticatedGroupsNameRoute: AuthenticatedGroupsNameRoute,
  AuthenticatedGroupsNewRoute: AuthenticatedGroupsNewRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedGroupsNameEditRoute: AuthenticatedGroupsNameEditRoute,
}

const AuthenticatedGroupsRouteWithChildren =
  AuthenticatedGroupsRoute._addFileChildren(AuthenticatedGroupsRouteChildren)

interface AuthenticatedHostKeysRouteChildren {
  AuthenticatedHostKeysNameRoute: typeof AuthenticatedHostKeysNameRoute
  AuthenticatedHostKeysNewRoute: typeof AuthenticatedHostKeysNewRoute
  AuthenticatedHostKeysIndexRoute: typeof AuthenticatedHostKeysIndexRoute
  AuthenticatedHostKeysNameEditRoute: typeof AuthenticatedHostKeysNameEditRoute
}

const AuthenticatedHostKeysRouteChildren: AuthenticatedHostKeysRouteChildren = {
  AuthenticatedHostKeysNameRoute: AuthenticatedHostKeysNameRoute,
  AuthenticatedHostKeysNewRoute: AuthenticatedHostKeysNewRoute,
  AuthenticatedHostKeysIndexRoute: AuthenticatedHostKeysIndexRoute,
  AuthenticatedHostKeysNameEditRoute: AuthenticatedHostKeysNameEditRoute,
}

const AuthenticatedHostKeysRouteWithChildren =
  AuthenticatedHostKeysRoute._addFileChildren(
    AuthenticatedHostKeysRouteChildren,
  )

interface AuthenticatedModelsNameRouteChildren {
  AuthenticatedModelsNameEditRoute: typeof AuthenticatedModelsNameEditRoute
}

const AuthenticatedModelsNameRouteChildren: AuthenticatedModelsNameRouteChildren =
  {
    AuthenticatedModelsNameEditRoute: AuthenticatedModelsNameEditRoute,
  }

const AuthenticatedModelsNameRouteWithChildren =
  AuthenticatedModelsNameRoute._addFileChildren(
    AuthenticatedModelsNameRouteChildren,
  )

interface AuthenticatedModelsRouteChildren {
  AuthenticatedModelsNameRoute: typeof AuthenticatedModelsNameRouteWithChildren
  AuthenticatedModelsNewRoute: typeof AuthenticatedModelsNewRoute
  AuthenticatedModelsIndexRoute: typeof AuthenticatedModelsIndexRoute
}

const AuthenticatedModelsRouteChildren: AuthenticatedModelsRouteChildren = {
  AuthenticatedModelsNameRoute: AuthenticatedModelsNameRouteWithChildren,
  AuthenticatedModelsNewRoute: AuthenticatedModelsNewRoute,
  AuthenticatedModelsIndexRoute: AuthenticatedModelsIndexRoute,
}

const AuthenticatedModelsRouteWithChildren =
  AuthenticatedModelsRoute._addFileChildren(AuthenticatedModelsRouteChildren)

interface AuthenticatedPoliciesRouteChildren {
  AuthenticatedPoliciesNameRoute: typeof AuthenticatedPoliciesNameRoute
  AuthenticatedPoliciesNewRoute: typeof AuthenticatedPoliciesNewRoute
  AuthenticatedPoliciesIndexRoute: typeof AuthenticatedPoliciesIndexRoute
  AuthenticatedPoliciesNameEditRoute: typeof AuthenticatedPoliciesNameEditRoute
  AuthenticatedPoliciesRateLimitsNameRoute: typeof AuthenticatedPoliciesRateLimitsNameRoute
  AuthenticatedPoliciesRateLimitsNewRoute: typeof AuthenticatedPoliciesRateLimitsNewRoute
  AuthenticatedPoliciesRateLimitsNameEditRoute: typeof AuthenticatedPoliciesRateLimitsNameEditRoute
}

const AuthenticatedPoliciesRouteChildren: AuthenticatedPoliciesRouteChildren = {
  AuthenticatedPoliciesNameRoute: AuthenticatedPoliciesNameRoute,
  AuthenticatedPoliciesNewRoute: AuthenticatedPoliciesNewRoute,
  AuthenticatedPoliciesIndexRoute: AuthenticatedPoliciesIndexRoute,
  AuthenticatedPoliciesNameEditRoute: AuthenticatedPoliciesNameEditRoute,
  AuthenticatedPoliciesRateLimitsNameRoute:
    AuthenticatedPoliciesRateLimitsNameRoute,
  AuthenticatedPoliciesRateLimitsNewRoute:
    AuthenticatedPoliciesRateLimitsNewRoute,
  AuthenticatedPoliciesRateLimitsNameEditRoute:
    AuthenticatedPoliciesRateLimitsNameEditRoute,
}

const AuthenticatedPoliciesRouteWithChildren =
  AuthenticatedPoliciesRoute._addFileChildren(
    AuthenticatedPoliciesRouteChildren,
  )

interface AuthenticatedPricingRouteChildren {
  AuthenticatedPricingNameRoute: typeof AuthenticatedPricingNameRoute
  AuthenticatedPricingNewRoute: typeof AuthenticatedPricingNewRoute
  AuthenticatedPricingIndexRoute: typeof AuthenticatedPricingIndexRoute
  AuthenticatedPricingNameEditRoute: typeof AuthenticatedPricingNameEditRoute
}

const AuthenticatedPricingRouteChildren: AuthenticatedPricingRouteChildren = {
  AuthenticatedPricingNameRoute: AuthenticatedPricingNameRoute,
  AuthenticatedPricingNewRoute: AuthenticatedPricingNewRoute,
  AuthenticatedPricingIndexRoute: AuthenticatedPricingIndexRoute,
  AuthenticatedPricingNameEditRoute: AuthenticatedPricingNameEditRoute,
}

const AuthenticatedPricingRouteWithChildren =
  AuthenticatedPricingRoute._addFileChildren(AuthenticatedPricingRouteChildren)

interface AuthenticatedServiceAccountsRouteChildren {
  AuthenticatedServiceAccountsNameRoute: typeof AuthenticatedServiceAccountsNameRoute
  AuthenticatedServiceAccountsNewRoute: typeof AuthenticatedServiceAccountsNewRoute
  AuthenticatedServiceAccountsIndexRoute: typeof AuthenticatedServiceAccountsIndexRoute
  AuthenticatedServiceAccountsNameEditRoute: typeof AuthenticatedServiceAccountsNameEditRoute
}

const AuthenticatedServiceAccountsRouteChildren: AuthenticatedServiceAccountsRouteChildren =
  {
    AuthenticatedServiceAccountsNameRoute:
      AuthenticatedServiceAccountsNameRoute,
    AuthenticatedServiceAccountsNewRoute: AuthenticatedServiceAccountsNewRoute,
    AuthenticatedServiceAccountsIndexRoute:
      AuthenticatedServiceAccountsIndexRoute,
    AuthenticatedServiceAccountsNameEditRoute:
      AuthenticatedServiceAccountsNameEditRoute,
  }

const AuthenticatedServiceAccountsRouteWithChildren =
  AuthenticatedServiceAccountsRoute._addFileChildren(
    AuthenticatedServiceAccountsRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsPayloadLoggingRoute: typeof AuthenticatedSettingsPayloadLoggingRoute
  AuthenticatedSettingsPermissionsRoute: typeof AuthenticatedSettingsPermissionsRoute
  AuthenticatedSettingsProxyModeRoute: typeof AuthenticatedSettingsProxyModeRoute
  AuthenticatedSettingsRateLimitsRoute: typeof AuthenticatedSettingsRateLimitsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsPayloadLoggingRoute:
    AuthenticatedSettingsPayloadLoggingRoute,
  AuthenticatedSettingsPermissionsRoute: AuthenticatedSettingsPermissionsRoute,
  AuthenticatedSettingsProxyModeRoute: AuthenticatedSettingsProxyModeRoute,
  AuthenticatedSettingsRateLimitsRoute: AuthenticatedSettingsRateLimitsRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBootstrapRoute: typeof AuthenticatedBootstrapRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRouteWithChildren
  AuthenticatedHostKeysRoute: typeof AuthenticatedHostKeysRouteWithChildren
  AuthenticatedKeysRoute: typeof AuthenticatedKeysRoute
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRouteWithChildren
  AuthenticatedPoliciesRoute: typeof AuthenticatedPoliciesRouteWithChildren
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRouteWithChildren
  AuthenticatedServiceAccountsRoute: typeof AuthenticatedServiceAccountsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedHostsNameRoute: typeof AuthenticatedHostsNameRoute
  AuthenticatedKeysNameRoute: typeof AuthenticatedKeysNameRoute
  AuthenticatedKeysNewRoute: typeof AuthenticatedKeysNewRoute
  AuthenticatedLogsRequestIdRoute: typeof AuthenticatedLogsRequestIdRoute
  AuthenticatedProvidersNameRoute: typeof AuthenticatedProvidersNameRoute
  AuthenticatedLogsIndexRoute: typeof AuthenticatedLogsIndexRoute
  AuthenticatedKeysNameEditRoute: typeof AuthenticatedKeysNameEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBootstrapRoute: AuthenticatedBootstrapRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRouteWithChildren,
  AuthenticatedHostKeysRoute: AuthenticatedHostKeysRouteWithChildren,
  AuthenticatedKeysRoute: AuthenticatedKeysRoute,
  AuthenticatedModelsRoute: AuthenticatedModelsRouteWithChildren,
  AuthenticatedPoliciesRoute: AuthenticatedPoliciesRouteWithChildren,
  AuthenticatedPricingRoute: AuthenticatedPricingRouteWithChildren,
  AuthenticatedServiceAccountsRoute:
    AuthenticatedServiceAccountsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedHostsNameRoute: AuthenticatedHostsNameRoute,
  AuthenticatedKeysNameRoute: AuthenticatedKeysNameRoute,
  AuthenticatedKeysNewRoute: AuthenticatedKeysNewRoute,
  AuthenticatedLogsRequestIdRoute: AuthenticatedLogsRequestIdRoute,
  AuthenticatedProvidersNameRoute: AuthenticatedProvidersNameRoute,
  AuthenticatedLogsIndexRoute: AuthenticatedLogsIndexRoute,
  AuthenticatedKeysNameEditRoute: AuthenticatedKeysNameEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
